const calculusTermsList = [
    {
      name: "Abscissa",
      formula: "The horizontal coordinate of a point in a Cartesian plane, representing its distance from the vertical axis.",
      fields: [],
      category: "Coordinates and Geometry",
    },
    {
      name: "Absolute Value",
      formula: "A measure of a number's magnitude regardless of its sign, denoting its distance from zero on a number line.",
      fields: [],
      category: "Functions and Rates of Change",
    },
    {
      name: "Acceleration",
      formula: "The rate at which an object's velocity changes with respect to time, expressed as a vector indicating direction and magnitude.",
      fields: [],
      category: "Motion and Dynamics",
    },
    {
      name: "Amplitude",
      formula: "The maximum displacement of a periodic function or oscillation from its equilibrium position.",
      fields: [],
      category: "Oscillatory Motion",
    },
    {
      name: "Angle",
      formula: "The rotational measurement between two intersecting lines or surfaces, often quantified in degrees or radians.",
      fields: [],
      category: "Geometry and Trigonometry",
    },
    {
      name: "Angular Velocity",
      formula: "The rate of change of angular displacement, indicating how quickly an object rotates around a specific axis.",
      fields: [],
      category: "Motion and Dynamics",
    },
    {
      name: "Antiderivative",
      formula: "A function whose derivative equals the given function, often associated with indefinite integration.",
      fields: [],
      category: "Integration",
    },
    {
      name: "Approximation by Differentials",
      formula: "A technique for estimating the change in a function using its derivative and small increments in its variable.",
      fields: [],
      category: "Differentiation",
    },
    {
      name: "Arclength",
      formula: "The total length of a curve, calculated as the integral of the curve's infinitesimal segments.",
      fields: [],
      category: "Geometry and Calculus",
    },
    {
      name: "Area",
      formula: "A measure of the two-dimensional space enclosed within a boundary, often determined using integrals.",
      fields: [],
      category: "Geometry and Calculus",
    },
    {
      name: "Argument",
      formula: "The independent variable of a function, especially in trigonometric or complex functions, which determines the function's output.",
      fields: [],
      category: "Functions",
    },
    {
      name: "Asymptote",
      formula: "A line that a curve approaches but never intersects or reaches as it extends infinitely in one or both directions.",
      fields: [],
      category: "Graph Analysis",
    },
    {
      name: "Average Rate of Change",
      formula: "The ratio of the change in a function's value to the change in the input variable, representing a slope over an interval.",
      fields: [],
      category: "Functions and Rates of Change",
    },
    {
      name: "Average Value of a Function",
      formula: "The mean of a function's values over a specific interval, calculated as the integral of the function divided by the interval's length.",
      fields: [],
      category: "Functions and Integration",
    },
    {
      name: "Average Velocity",
      formula: "The total displacement divided by the total time taken, representing the overall rate of motion over a time interval.",
      fields: [],
      category: "Motion and Dynamics",
    },
    {
      name: "Axis of Revolution",
      formula: "A line about which a two-dimensional shape rotates to generate a three-dimensional solid.",
      fields: [],
      category: "Geometry and Calculus",
    },
    {
      name: "Binomial Series",
      formula: "An infinite expansion of expressions raised to a power, generalizing the binomial theorem for real or complex exponents.",
      fields: [],
      category: "Series and Convergence",
    },
    {
      name: "Bounded Sequence",
      formula: "A sequence whose terms are confined within a finite range, having both upper and lower limits.",
      fields: [],
      category: "Sequences and Series",
    },
    {
      name: "Cardioid",
      formula: "A heart-shaped curve traced by a point on a circle rolling around another circle of equal radius.",
      fields: [],
      category: "Coordinates and Geometry",
    },
    {
      name: "Catenary",
      formula: "The curve formed by a hanging flexible chain or cable under its own weight, described mathematically as a hyperbolic cosine.",
      fields: [],
      category: "Geometry and Trigonometry",
    },
    {
      name: "Center of Curvature",
      formula: "The point at a given location on a curve where the osculating circle is centered, representing the curve's maximum bending at that point.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Centroid",
      formula: "The geometric center of a plane figure or solid body, often corresponding to the average position of all points within it.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Chain Rule",
      formula: "A fundamental differentiation rule that allows the derivative of a composite function to be expressed in terms of the derivatives of its components.",
      fields: [],
      category: "Differentiation",
    },
    {
      name: "Circle",
      formula: "A set of all points in a plane equidistant from a fixed central point.",
      fields: [],
      category: "Coordinates and Geometry",
    },
    {
      name: "Closed Interval",
      formula: "A range of real numbers that includes its endpoints, denoted as [a, b].",
      fields: [],
      category: "Intervals and Sets",
    },
    {
      name: "Comparison Test",
      formula: "A method for determining the convergence or divergence of a series by comparing it to another series with known behavior.",
      fields: [],
      category: "Series and Convergence",
    },
    {
      name: "Composite Function",
      formula: "A function formed by applying one function to the results of another, expressed as f(g(x)).",
      fields: [],
      category: "Functions",
    },
    {
      name: "Concavity",
      formula: "A property describing the curvature of a graph, where a function is concave up if its slope increases and concave down if it decreases.",
      fields: [],
      category: "Graph Analysis",
    },
    {
      name: "Conic Sections",
      formula: "Curves obtained by intersecting a plane with a cone, resulting in shapes like circles, ellipses, parabolas, and hyperbolas.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Continuous Function",
      formula: "A function that has no breaks, jumps, or holes in its domain, allowing it to be drawn without lifting the pen.",
      fields: [],
      category: "Functions",
    },
    {
      name: "Convergence",
      formula: "A property of a sequence or series approaching a finite limit as its terms progress to infinity.",
      fields: [],
      category: "Series and Convergence",
    },
    {
      name: "Coordinate System",
      formula: "A framework used to locate points in space, typically defined by axes such as Cartesian, polar, or cylindrical coordinates.",
      fields: [],
      category: "Coordinates and Geometry",
    },
    {
      name: "Curvature",
      formula: "A measure of how sharply a curve deviates from being a straight line at a given point.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Differential Equations",
      formula: "Equations involving derivatives that describe how a function changes in relation to its variables.",
      fields: [],
      category: "Differential Equations",
    },
    {
      name: "Direction Field",
      formula: "A graphical representation showing the slope of solutions to a differential equation at various points.",
      fields: [],
      category: "Differential Equations",
    },
    {
      name: "Divergence",
      formula: "A measure of how a vector field spreads out from a point, often computed as the dot product of the del operator with the field.",
      fields: [],
      category: "Vector Calculus",
    },
    {
      name: "Domain and Range",
      formula: "The domain is the set of all input values for which a function is defined, and the range is the set of all resulting output values.",
      fields: [],
      category: "Functions",
    },
    {
      name: "Ellipse",
      formula: "A closed curve in which the sum of the distances from any point on the curve to two fixed points (foci) is constant.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Fourier Series",
      formula: "A representation of periodic functions as an infinite sum of sines and cosines, each with specific coefficients.",
      fields: [],
      category: "Series and Convergence",
    },
    {
      name: "Gradient",
      formula: "A vector indicating the direction of the steepest ascent of a scalar field, derived from its partial derivatives.",
      fields: [],
      category: "Vector Calculus",
    },
    {
      name: "Harmonic Motion",
      formula: "Oscillatory motion, such as that of a pendulum, described mathematically by sinusoidal functions.",
      fields: [],
      category: "Oscillatory Motion",
    },
    {
      name: "Hyperbola",
      formula: "A curve formed by the intersection of a plane with a double cone, characterized by two separate branches.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Inflection Point",
      formula: "A point on a curve where the concavity changes direction.",
      fields: [],
      category: "Graph Analysis",
    },
    {
      name: "Integrand",
      formula: "The function being integrated in an integral expression.",
      fields: [],
      category: "Integration",
    },
    {
      name: "Limit",
      formula: "The value a function or sequence approaches as the input or index approaches a specific point or infinity.",
      fields: [],
      category: "Limits",
    },
    {
      name: "Local Extremum",
      formula: "The highest or lowest value of a function in a specific region, occurring at a local maximum or minimum.",
      fields: [],
      category: "Functions and Graphs",
    },
    {
      name: "Parabola",
      formula: "A symmetric curve where any point is equidistant from a fixed focus and a directrix.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Parametric Equations",
      formula: "Equations defining a curve using a parameter to express coordinates as functions of that parameter.",
      fields: [],
      category: "Graphing",
    },
    {
      name: "Partial Derivative",
      formula: "The derivative of a multivariable function with respect to one variable while keeping others constant.",
      fields: [],
      category: "Differentiation",
    },
    {
      name: "Path Integral",
      formula: "An integral that computes a quantity along a curve, often used in physics for work or line integrals.",
      fields: [],
      category: "Integration",
    },
    {
      name: "Polar Coordinates",
      formula: "A coordinate system where a point's location is determined by its distance from the origin and angle from a reference direction.",
      fields: [],
      category: "Coordinates and Geometry",
    },
    {
      name: "Radius of Curvature",
      formula: "The reciprocal of curvature, representing the radius of the osculating circle at a point on a curve.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Rectilinear Motion",
      formula: "Motion along a straight line, described by functions of time.",
      fields: [],
      category: "Motion and Dynamics",
    },
    {
      name: "Series",
      formula: "The sum of terms in a sequence, which may converge to a finite value or diverge to infinity.",
      fields: [],
      category: "Series and Convergence",
    },
    {
      name: "Slope",
      formula: "The ratio of the vertical change to the horizontal change between two points on a line or curve.",
      fields: [],
      category: "Graph Analysis",
    },
    {
      name: "Surface Area",
      formula: "The total area covering the outer surface of a three-dimensional object, computed using integration for curved surfaces.",
      fields: [],
      category: "Geometry",
    },
    {
      name: "Tangent Line/Plane",
      formula: "A line or plane that touches a curve or surface at a single point without crossing it locally.",
      fields: [],
      category: "Graph Analysis",
    },
    {
      name: "Velocity",
      formula: "The rate of change of an object’s position with respect to time, described as a vector quantity.",
      fields: [],
      category: "Motion and Dynamics",
    },
    {
      name: "Vector Fields",
      formula: "A function assigning a vector to every point in space, used to model physical phenomena like fluid flow or gravitational fields.",
      fields: [],
      category: "Vector Calculus",
    },
  ];
  
  export default calculusTermsList;
  