import { useState, useEffect, useRef } from 'react';
import QuizWidget from '../examples/quiz/QuizWidget'
import generatePythagoreanTripleQuestion from '../examples/quiz/questions/pythagoreanTripleQuestions';

// =========================================================
//   PythagoreanTriplesPage
//   Main page component for /tables/arithmetics/pythagorean-triples.
//   Props:
//     relatedReferences  array  [{ title, sub, href }] — sidebar links
// =========================================================

// ---------- Theme: indigo (matches PerfectSquaresPage / PerfectCubesPage) ----------
const C = {
  primary:      '#4f46e5',
  primaryDark:  '#3730a3',
  primaryLight: '#eef2ff',
  bg:           '#fafbff',
  border:       '#e0e7ff',
  borderSoft:   '#eef0f7',
  text:         '#1e1b4b',
  textMuted:    '#64748b',
  success:      '#10b981',
  successBg:    '#d1fae5',
  error:        '#ef4444',
  errorBg:      '#fee2e2',
  errorText:    '#991b1b',
  warn:         '#f59e0b',
  warnBg:       '#fef3c7',
  warnText:     '#92400e',
  shadowSm:     '0 1px 2px rgba(15,23,42,0.04), 0 1px 3px rgba(15,23,42,0.06)',
  shadowMd:     '0 4px 12px rgba(15,23,42,0.08)',
  shadowLg:     '0 8px 24px rgba(15,23,42,0.10)',
};

// ---------- Helpers ----------
const gcd = (a, b) => b === 0 ? a : gcd(b, a % b);
const isPrime = (n) => {
  if (n < 2) return false;
  for (let i = 2; i * i <= n; i++) if (n % i === 0) return false;
  return true;
};
const isPerfectSquare = (n) => {
  if (n < 0) return false;
  const r = Math.round(Math.sqrt(n));
  return r * r === n;
};

const TABLE_MAX_C = 100;

// ---------- Precomputed: triples (Euclid + multiples, c <= 100) ----------
const TRIPLES = (() => {
  const list = [];
  const seen = new Set();
  for (let m = 2; m <= 20; m++) {
    for (let n = 1; n < m; n++) {
      if ((m - n) % 2 === 0) continue;
      if (gcd(m, n) !== 1) continue;
      const pa = m * m - n * n;
      const pb = 2 * m * n;
      const pc = m * m + n * n;
      const aLow = Math.min(pa, pb);
      const aHigh = Math.max(pa, pb);
      for (let k = 1; k * pc <= TABLE_MAX_C; k++) {
        const a = aLow * k;
        const b = aHigh * k;
        const c = pc * k;
        const id = `${a}-${b}-${c}`;
        if (seen.has(id)) continue;
        seen.add(id);
        list.push({
          id, a, b, c,
          primitive: k === 1,
          m, n, k,
          basePrim: { a: aLow, b: aHigh, c: pc },
        });
      }
    }
  }
  list.sort((x, y) => x.c - y.c || x.a - y.a);
  return list;
})();

// ---------- Precomputed: filter sets (sets of triple ids) ----------
const FILTER_SETS = (() => {
  const sets = {
    primitive: new Set(),
    primeHyp:  new Set(),
    squareLeg: new Set(),
    twinMn:    new Set(),
    family345: new Set(),
  };
  TRIPLES.forEach(t => {
    if (t.primitive) sets.primitive.add(t.id);
    if (isPrime(t.c)) sets.primeHyp.add(t.id);
    if (isPerfectSquare(t.a) || isPerfectSquare(t.b)) sets.squareLeg.add(t.id);
    if (t.primitive && (t.m - t.n === 1)) sets.twinMn.add(t.id);
    if (t.basePrim.a === 3 && t.basePrim.b === 4 && t.basePrim.c === 5) sets.family345.add(t.id);
  });
  return sets;
})();

const FILTER_DEFS = [
  { id: 'primitive', icon: '\u25C8', title: 'Primitive triples only',
    desc: 'Triples whose three values share no common factor \u2014 the building blocks of all triples.' },
  { id: 'primeHyp', icon: 'p', title: 'Prime hypotenuse',
    desc: 'Triples whose hypotenuse c is a prime number.' },
  { id: 'squareLeg', icon: 'n\u00B2', title: 'Square leg',
    desc: 'Triples containing a perfect square as one of their legs.' },
  { id: 'twinMn', icon: 'm\u2212n=1', title: 'Consecutive m, n',
    desc: 'Primitive triples where m and n differ by 1 \u2014 the near-isosceles family like (3, 4, 5) and (20, 21, 29).' },
  { id: 'family345', icon: '3\u00B7k', title: '(3, 4, 5) family',
    desc: 'Every multiple of the (3, 4, 5) triple.' },
];

const PROPERTY_CARDS = [
  {
    icon: 'E',
    title: 'Euclid\u2019s formula',
    body: 'Every primitive triple is generated by integers m &gt; n &gt; 0 with gcd(m,n)=1 and m\u2212n odd: a = m\u00B2 \u2212 n\u00B2, b = 2mn, c = m\u00B2 + n\u00B2.',
    code: 'm=2, n=1 \u2192 (3, 4, 5) \u00B7 m=3, n=2 \u2192 (5, 12, 13)',
    hasMnGrid: true,
  },
  {
    icon: '\u00B1',
    title: 'Parity of legs',
    body: 'In any primitive triple, exactly one leg is even and one is odd; the hypotenuse is always odd. So legs can\u2019t both be odd or both even.',
    code: '(3, 4, 5): odd, even, odd \u2713',
  },
  {
    icon: '\u00F7',
    title: 'Divisibility rules',
    body: 'In every triple, one leg is divisible by 3, one by 4, and one of the three values by 5. The area ab/2 is always divisible by 6.',
    code: '(5, 12, 13): 12 \u00F7 3 = 4, 12 \u00F7 4 = 3, 5 \u00F7 5 = 1',
  },
  {
    icon: 'r',
    title: 'Integer inradius',
    body: 'The inscribed circle of a right triangle with integer legs has integer radius r = (a + b \u2212 c) / 2. Always.',
    code: '(8, 15, 17): r = (8 + 15 \u2212 17) / 2 = 3',
  },
];

const TOC_ITEMS = [
  { id: 'sec-tool',       label: 'Triple tool' },
  { id: 'sec-table',      label: 'The table' },
  { id: 'sec-patterns',   label: 'Patterns & filters' },
  { id: 'sec-properties', label: 'Properties' },
  { id: 'sec-quiz',       label: 'Test yourself' },
];

const LEGEND_PILLS = [
  { kind: 'primitive', label: 'Primitive triple' },
  { kind: 'multiple',  label: 'Multiple of a primitive' },
];
const PILL_STYLES = {
  primitive: { bg: C.primaryLight, fg: C.primaryDark },
  multiple:  { bg: '#f1f5f9', fg: '#475569' },
};

// ---------- Inline styles ----------
const S = {
  container: {
    maxWidth: '1000px',
    margin: '0 auto',
    padding: '28px 24px 80px',
    position: 'relative',
    fontFamily: "'Inter', -apple-system, BlinkMacSystemFont, sans-serif",
    color: C.text,
  },
  pageLayout: {
    position: 'relative',
  },
  sidebar: {
    position: 'absolute',
    top: 0,
    right: '100%',
    width: '240px',
    height: '100%',
    marginRight: '40px',
  },
  sidebarSticky: {
    position: 'sticky',
    top: '20px',
    maxHeight: 'calc(100vh - 40px)',
    overflowY: 'auto',
    paddingRight: '4px',
  },
  sidebarBlock: { marginBottom: '32px' },
  sidebarLabel: {
    fontSize: '11px', textTransform: 'uppercase', letterSpacing: '1.2px',
    color: C.textMuted, fontWeight: 700, marginBottom: '14px', paddingLeft: '14px',
  },
  tocList: { listStyle: 'none', margin: 0, padding: 0 },
  tocLinkBase: {
    display: 'flex', alignItems: 'center', gap: '10px',
    padding: '9px 0 9px 14px', borderLeft: `2px solid ${C.borderSoft}`,
    color: C.textMuted, textDecoration: 'none', fontSize: '14px',
    lineHeight: 1.3, cursor: 'pointer', transition: 'all 0.15s',
  },
  tocNumBase: {
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    width: '22px', height: '22px', borderRadius: '50%',
    background: C.borderSoft, color: C.textMuted,
    fontSize: '11px', fontWeight: 700, flexShrink: 0, transition: 'all 0.15s',
  },
  relatedMini: {
    display: 'block', padding: '11px 14px', background: 'white',
    border: `1px solid ${C.borderSoft}`, borderRadius: '9px',
    textDecoration: 'none', color: 'inherit',
    marginBottom: '8px', transition: 'all 0.15s', cursor: 'pointer',
  },
  relatedMiniTitle: { fontWeight: 600, color: C.primaryDark, fontSize: '13px', marginBottom: '2px' },
  relatedMiniSub: { fontSize: '12px', color: C.textMuted },
  mainCol: { minWidth: 0, width: '100%' },
  toolSection: {
    background: 'linear-gradient(135deg, #eef2ff 0%, #f0f9ff 100%)',
    border: `1px solid ${C.border}`, borderRadius: '20px',
    padding: '28px 32px', marginBottom: '36px',
    position: 'relative', overflow: 'hidden',
  },
  toolHeader: { position: 'relative', zIndex: 1, marginBottom: '18px' },
  toolH2: {
    fontFamily: "'Crimson Pro', serif", fontSize: '26px',
    color: C.primaryDark, margin: '0 0 4px 0', fontWeight: 700,
  },
  toolSub: { color: C.textMuted, fontSize: '14px', margin: 0 },
  modeTabsWrap: {
    position: 'relative', zIndex: 1, display: 'inline-flex',
    background: 'white', borderRadius: '12px', padding: '4px',
    marginBottom: '14px', border: `1px solid ${C.border}`,
    boxShadow: C.shadowSm, gap: '2px', flexWrap: 'wrap',
  },
  modeTabBase: {
    padding: '9px 18px', borderRadius: '9px', fontSize: '14px',
    fontWeight: 600, cursor: 'pointer', background: 'transparent',
    border: 'none', transition: 'all 0.18s',
    fontFamily: 'inherit', color: C.textMuted,
  },
  modeTabActive: {
    background: C.primary, color: 'white',
    boxShadow: '0 2px 6px rgba(79, 70, 229, 0.30)',
  },
  inputBlock: {
    display: 'flex', gap: '10px', marginBottom: '8px',
    position: 'relative', zIndex: 1,
    alignItems: 'center', flexWrap: 'wrap',
  },
  inputField: {
    flex: 1, minWidth: '140px', padding: '13px 18px',
    border: `2px solid ${C.border}`, borderRadius: '11px',
    fontSize: '15px', outline: 'none', background: 'white',
    transition: 'border-color 0.15s, box-shadow 0.15s',
    fontFamily: 'inherit', color: C.text,
  },
  inputFieldNarrow: { minWidth: '90px' },
  inputBtn: {
    padding: '13px 26px', background: C.primary, color: 'white',
    border: 'none', borderRadius: '11px',
    fontWeight: 600, fontSize: '15px', cursor: 'pointer',
    transition: 'background 0.15s, transform 0.1s',
    fontFamily: 'inherit', whiteSpace: 'nowrap',
  },
  toolStatus: {
    marginTop: '12px', padding: '11px 14px',
    background: 'rgba(255, 255, 255, 0.75)',
    border: `1px solid ${C.border}`, borderRadius: '10px',
    display: 'flex', alignItems: 'flex-start', gap: '10px',
    fontSize: '14px', color: C.text, lineHeight: 1.55,
    position: 'relative', zIndex: 1,
  },
  statusIcon: {
    width: '22px', height: '22px', borderRadius: '50%',
    display: 'inline-flex', alignItems: 'center', justifyContent: 'center',
    color: 'white', fontSize: '13px', fontWeight: 700,
    flexShrink: 0, marginTop: '1px',
  },
  legend: {
    background: 'white', borderRadius: '16px', padding: '18px 22px',
    marginBottom: '22px', border: `1px solid ${C.borderSoft}`,
    boxShadow: C.shadowSm,
  },
  legendTitle: {
    fontSize: '12px', textTransform: 'uppercase', letterSpacing: '1px',
    color: C.textMuted, fontWeight: 700, marginBottom: '12px',
  },
  legendRow: { display: 'flex', flexWrap: 'wrap', gap: '8px', marginBottom: '10px' },
  legendPillBase: { padding: '6px 13px', borderRadius: '9999px', fontSize: '13px', fontWeight: 600 },
  legendNote: { fontSize: '14px', color: C.textMuted, margin: 0 },
  filterStatus: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    padding: '12px 18px',
    background: 'linear-gradient(90deg, #fef3c7 0%, #fffbeb 100%)',
    border: `1px solid ${C.warn}`, borderRadius: '10px',
    marginBottom: '16px', fontSize: '14px',
  },
  filterStatusText: { color: C.warnText, fontWeight: 600 },
  filterClear: {
    background: 'white', border: `1px solid ${C.warn}`,
    color: C.warnText, padding: '5px 12px', borderRadius: '7px',
    fontSize: '13px', fontWeight: 600, cursor: 'pointer', fontFamily: 'inherit',
  },
  tripleGrid: {
    display: 'grid', gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '14px', marginBottom: '36px',
  },
  tripleCardBase: {
    background: 'white',
    border: `1px solid ${C.borderSoft}`,
    borderRadius: '12px',
    padding: '20px 10px 12px',
    cursor: 'pointer',
    transition: 'transform 0.15s, box-shadow 0.15s, border-color 0.15s, opacity 0.2s',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    gap: '8px',
    position: 'relative',
  },
  tripleCardMultipleBg: { background: '#f8fafc' },
  tripleSvgWrap: {
    height: '70px',
    width: '100%',
    display: 'flex',
    alignItems: 'flex-end',
    justifyContent: 'center',
  },
  tripleValues: {
    fontWeight: 700,
    fontSize: '14px',
    color: C.text,
    letterSpacing: '0.2px',
  },
  tripleMeta: {
    fontSize: '11px',
    color: C.textMuted,
    fontWeight: 500,
  },
  tripleBadgeBase: {
    position: 'absolute',
    top: '6px',
    right: '6px',
    fontSize: '9px',
    fontWeight: 700,
    textTransform: 'uppercase',
    letterSpacing: '0.5px',
    padding: '2px 6px',
    borderRadius: '4px',
  },
  cellDetails: {
    background: 'white', border: `1px solid ${C.border}`,
    borderRadius: '18px', padding: '28px',
    marginBottom: '44px', position: 'relative', boxShadow: C.shadowLg,
  },
  closeDetails: {
    position: 'absolute', top: '16px', right: '16px',
    width: '32px', height: '32px', border: 'none',
    background: C.borderSoft, borderRadius: '50%',
    fontSize: '20px', cursor: 'pointer', color: C.textMuted,
    lineHeight: 1, transition: 'background 0.15s', fontFamily: 'inherit',
  },
  detailsH3: {
    fontFamily: "'Crimson Pro', serif", fontSize: '30px',
    color: C.primaryDark, fontWeight: 700, margin: '0 0 20px 0',
  },
  detailGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))',
    gap: '12px',
  },
  detailItem: {
    padding: '14px 16px', background: C.bg,
    borderRadius: '10px', border: `1px solid ${C.borderSoft}`,
  },
  detailLabel: {
    fontSize: '11px', textTransform: 'uppercase', letterSpacing: '0.8px',
    color: C.textMuted, marginBottom: '6px', fontWeight: 700,
  },
  detailValue: { fontSize: '16px', fontWeight: 700, color: C.text },
  propertyBadges: { display: 'flex', flexWrap: 'wrap', gap: '8px' },
  badge: {
    padding: '5px 12px', background: C.primaryLight,
    color: C.primaryDark, borderRadius: '9999px',
    fontSize: '12px', fontWeight: 600, border: `1px solid ${C.border}`,
  },
  sectionH: {
    fontFamily: "'Crimson Pro', serif", fontSize: '30px',
    color: '#1e3a8a', fontWeight: 700, letterSpacing: '-0.3px',
    margin: '0 0 8px 0',
  },
  sectionSub: { color: C.textMuted, marginBottom: '26px', fontSize: '15px' },
  filterGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(220px, 1fr))',
    gap: '16px', marginBottom: '40px',
  },
  filterCard: {
    background: 'white', border: `2px solid ${C.borderSoft}`,
    borderRadius: '14px', padding: '20px',
    cursor: 'pointer', transition: 'all 0.18s',
    position: 'relative', boxShadow: C.shadowSm,
  },
  filterIcon: {
    width: '44px', height: '44px',
    background: `linear-gradient(135deg, ${C.primary} 0%, #6366f1 100%)`,
    color: 'white', borderRadius: '12px',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: '16px', fontWeight: 700,
    fontFamily: "'Crimson Pro', serif", marginBottom: '14px',
    boxShadow: '0 4px 10px rgba(79,70,229,0.25)',
  },
  filterCardH3: { fontSize: '16px', fontWeight: 700, color: C.text, margin: '0 0 6px 0' },
  filterCardP: { color: C.textMuted, fontSize: '13px', marginBottom: '14px', lineHeight: 1.5 },
  filterCardFooter: {
    display: 'flex', alignItems: 'center', justifyContent: 'space-between',
    paddingTop: '12px', borderTop: `1px solid ${C.borderSoft}`,
  },
  filterCount: { fontSize: '13px', fontWeight: 700, color: C.primaryDark },
  filterAction: {
    fontSize: '12px', color: C.textMuted,
    textTransform: 'uppercase', letterSpacing: '0.6px', fontWeight: 600,
  },
  propertiesSection: { marginTop: '32px' },
  propertyGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(auto-fit, minmax(260px, 1fr))',
    gap: '16px',
  },
  propertyCard: {
    background: 'white', border: `1px solid ${C.borderSoft}`,
    borderRadius: '14px', padding: '22px', boxShadow: C.shadowSm,
  },
  propertyCardIcon: {
    width: '36px', height: '36px',
    background: C.primaryLight, color: C.primaryDark, borderRadius: '9px',
    display: 'flex', alignItems: 'center', justifyContent: 'center',
    fontSize: '17px', fontWeight: 700,
    fontFamily: "'Crimson Pro', serif", marginBottom: '12px',
  },
  propertyCardH4: { fontSize: '15px', fontWeight: 700, color: C.text, margin: '0 0 6px 0' },
  propertyCardP: { color: C.textMuted, fontSize: '13px', lineHeight: 1.55, margin: 0 },
  propertyCardCode: {
    display: 'block', fontFamily: "'Menlo', 'Monaco', monospace",
    background: C.bg, padding: '7px 11px', borderRadius: '6px',
    fontSize: '12px', marginTop: '8px',
    color: C.primaryDark, fontWeight: 600,
  },
  mnGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(7, 1fr)',
    gap: '3px',
    marginTop: '10px',
    background: C.bg,
    padding: '8px',
    borderRadius: '8px',
    maxWidth: '220px',
  },
  mnCellBase: {
    aspectRatio: '1',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: '9px',
    fontWeight: 700,
    borderRadius: '3px',
    color: C.textMuted,
    background: 'white',
  },
  mnCellHeader: {
    background: 'transparent',
    fontSize: '10px',
    color: C.primaryDark,
  },
  mnCellPrim: {
    background: C.primary,
    color: 'white',
  },
  mnCellFail: {
    background: C.errorBg,
    color: C.errorText,
  },
  mnCellEmpty: {
    background: 'transparent',
  },
  quizSection: { marginTop: '56px' },
};

// ---------- CSS (pseudo-classes, hover, media queries) ----------
const CSS = `
.ptp-toc-link:hover {
  color: ${C.primary};
}
.ptp-related-mini:hover {
  border-color: ${C.primary} !important;
  transform: translateX(2px);
  box-shadow: ${C.shadowSm};
}
.ptp-input-field:focus {
  border-color: ${C.primary} !important;
  box-shadow: 0 0 0 4px rgba(79,70,229,0.12);
}
.ptp-input-btn:hover { background: ${C.primaryDark} !important; }
.ptp-input-btn:active { transform: translateY(1px); }
.ptp-mode-tab:not(.active):hover { color: ${C.primary} !important; }
.ptp-triple-card:hover {
  transform: translateY(-2px);
  box-shadow: 0 6px 16px rgba(15,23,42,0.10);
  border-color: ${C.primary};
  z-index: 5;
}
.ptp-triple-card.highlight {
  border: 2px solid ${C.warn} !important;
  box-shadow: 0 0 0 3px rgba(245,158,11,0.35), 0 6px 16px rgba(245,158,11,0.25);
  transform: scale(1.05);
  z-index: 4;
}
.ptp-triple-card.filter-match {
  border: 2px solid ${C.warn} !important;
  box-shadow: 0 4px 14px rgba(245,158,11,0.35);
  transform: scale(1.04);
  z-index: 3;
}
.ptp-triple-card.filter-dim { opacity: 0.28; }
.ptp-filter-card:hover {
  transform: translateY(-3px);
  box-shadow: ${C.shadowMd};
  border-color: ${C.border} !important;
}
.ptp-filter-card.active {
  border-color: ${C.warn} !important;
  background: linear-gradient(135deg, #fffbeb 0%, #fef3c7 100%) !important;
  box-shadow: 0 0 0 4px rgba(245,158,11,0.18), ${C.shadowMd};
}
.ptp-filter-card.active::after {
  content: '\u25CF Active';
  position: absolute;
  top: 12px;
  right: 14px;
  font-size: 11px;
  font-weight: 700;
  color: ${C.warnText};
  letter-spacing: 0.5px;
}
.ptp-filter-card.active .ptp-filter-icon {
  background: linear-gradient(135deg, ${C.warn} 0%, #fb923c 100%) !important;
  box-shadow: 0 4px 10px rgba(245,158,11,0.3) !important;
}
.ptp-filter-card.active .ptp-filter-count,
.ptp-filter-card.active .ptp-filter-action {
  color: ${C.warnText} !important;
}
.ptp-sidebar-sticky::-webkit-scrollbar { width: 4px; }
.ptp-sidebar-sticky::-webkit-scrollbar-thumb { background: ${C.border}; border-radius: 4px; }
.ptp-close-details:hover { background: #e5e7eb !important; color: ${C.text} !important; }
@keyframes ptpSlideIn {
  from { opacity: 0; transform: translateY(-8px); }
  to { opacity: 1; transform: translateY(0); }
}
.ptp-cell-details { animation: ptpSlideIn 0.25s ease; }

/* Hide the absolute sidebar when the viewport is too narrow to fit it */
@media (max-width: 1320px) {
  .ptp-sidebar { display: none !important; }
}
@media (max-width: 900px) {
  .ptp-triple-grid { grid-template-columns: repeat(3, 1fr) !important; }
}
@media (max-width: 640px) {
  .ptp-triple-grid { grid-template-columns: repeat(2, 1fr) !important; }
  .ptp-input-block { flex-direction: column !important; align-items: stretch !important; }
  .ptp-input-block input { width: 100% !important; }
  .ptp-input-block button { width: 100% !important; }
  .ptp-mode-tab { padding: 9px 14px !important; font-size: 13px !important; }
}
`;

// ---------- SVG triangle (proportional to a:b) ----------
const TripleSvg = ({ a, b, primitive }) => {
  const target = 55;
  const scale = target / Math.max(a, b);
  const aPx = a * scale;
  const bPx = b * scale;
  const pad = 6;
  const w = bPx + pad * 2;
  const h = aPx + pad * 2;
  const x0 = pad;
  const y0 = pad + aPx;
  const fill = primitive ? 'rgba(79,70,229,0.15)' : 'rgba(100,116,139,0.13)';
  const stroke = primitive ? C.primary : C.textMuted;
  return (
    <svg
      viewBox={`0 0 ${w} ${h}`}
      width={w}
      height={h}
      preserveAspectRatio="xMidYMid meet"
    >
      <polygon
        points={`${x0},${y0} ${x0 + bPx},${y0} ${x0},${y0 - aPx}`}
        fill={fill}
        stroke={stroke}
        strokeWidth="1.5"
        strokeLinejoin="round"
      />
      <rect
        x={x0}
        y={y0 - 6}
        width="6"
        height="6"
        fill="none"
        stroke={stroke}
        strokeWidth="0.8"
      />
    </svg>
  );
};

// ---------- m,n parameter grid (for the Euclid property card) ----------
const MnGrid = () => {
  const cells = [];
  cells.push(
    <div key="h-corner" style={{ ...S.mnCellBase, ...S.mnCellHeader }}>
      m,n
    </div>
  );
  for (let n = 1; n <= 6; n++) {
    cells.push(
      <div key={`hn-${n}`} style={{ ...S.mnCellBase, ...S.mnCellHeader }}>
        {n}
      </div>
    );
  }
  for (let m = 2; m <= 7; m++) {
    cells.push(
      <div key={`hm-${m}`} style={{ ...S.mnCellBase, ...S.mnCellHeader }}>
        {m}
      </div>
    );
    for (let n = 1; n <= 6; n++) {
      if (n >= m) {
        cells.push(
          <div
            key={`${m}-${n}`}
            style={{ ...S.mnCellBase, ...S.mnCellEmpty }}
          />
        );
        continue;
      }
      const coprime = gcd(m, n) === 1;
      const opposite = (m - n) % 2 === 1;
      const ok = coprime && opposite;
      const cVal = m * m + n * n;
      cells.push(
        <div
          key={`${m}-${n}`}
          style={{ ...S.mnCellBase, ...(ok ? S.mnCellPrim : S.mnCellFail) }}
          title={ok ? `c=${cVal}` : 'invalid'}
        >
          {ok ? cVal : '\u00D7'}
        </div>
      );
    }
  }
  return <div style={S.mnGrid}>{cells}</div>;
};

// ---------- Component ----------
const PythagoreanTriplesPage = ({ relatedReferences = [] }) => {
  // Tool state
  const [mode, setMode] = useState('test');
  const [aInput, setAInput] = useState('');
  const [bInput, setBInput] = useState('');
  const [cInput, setCInput] = useState('');
  const [legInput, setLegInput] = useState('');
  const [hypInput, setHypInput] = useState('');

  const [statusKind, setStatusKind] = useState(null);
  const [statusIcon, setStatusIcon] = useState('');
  const [statusHtml, setStatusHtml] = useState('');

  // Table state
  const [detailsId, setDetailsId] = useState(null);
  const [highlightedIds, setHighlightedIds] = useState(() => new Set());
  const [activeFilter, setActiveFilter] = useState(null);

  // TOC + scroll plumbing
  const [activeSection, setActiveSection] = useState('sec-tool');
  const [pendingScroll, setPendingScroll] = useState(null);

  const cardRefs = useRef({});
  const sectionRefs = useRef({});

  // ===== Helpers =====
  const setStatus = (kind, icon, html) => {
    setStatusKind(kind); setStatusIcon(icon); setStatusHtml(html);
  };
  const hideStatus = () => {
    setStatusKind(null); setStatusIcon(''); setStatusHtml('');
  };
  const clearTableHighlights = () => {
    setActiveFilter(null);
    setHighlightedIds(new Set());
    setDetailsId(null);
  };

  // ===== Scroll resolver =====
  useEffect(() => {
    if (!pendingScroll) return;
    let el = null;
    if (pendingScroll.type === 'card') {
      el = cardRefs.current[pendingScroll.id];
    } else if (pendingScroll.type === 'table') {
      el = sectionRefs.current['sec-table'];
    } else if (pendingScroll.type === 'details') {
      el = document.getElementById('ptp-cell-details');
    }
    if (el) {
      el.scrollIntoView({
        behavior: 'smooth',
        block: pendingScroll.type === 'table' ? 'start' : 'center',
      });
    }
    setPendingScroll(null);
  }, [pendingScroll]);

  // ===== TOC active state =====
  useEffect(() => {
    const sections = TOC_ITEMS
      .map((item) => sectionRefs.current[item.id])
      .filter(Boolean);
    if (sections.length === 0) return;
    const obs = new IntersectionObserver((entries) => {
      entries.forEach((e) => {
        if (e.isIntersecting) setActiveSection(e.target.id);
      });
    }, { rootMargin: '-25% 0px -65% 0px' });
    sections.forEach((s) => obs.observe(s));
    return () => obs.disconnect();
  }, []);

  // ===== Mode change =====
  const handleModeChange = (next) => {
    setMode(next);
    hideStatus();
  };

  // ===== Tool: Mode 1 (Test triple) =====
  const runTest = () => {
    const a = parseInt(aInput, 10);
    const b = parseInt(bInput, 10);
    const c = parseInt(cInput, 10);
    if (isNaN(a) || isNaN(b) || isNaN(c) || a < 1 || b < 1 || c < 1) {
      setStatus('error', '!', 'Please enter three positive integers.');
      return;
    }
    setActiveFilter(null);
    setHighlightedIds(new Set());
    setDetailsId(null);

    const lo = Math.min(a, b);
    const hi = Math.max(a, b);
    const valid = lo * lo + hi * hi === c * c;
    if (!valid) {
      setStatus('error', '\u2717',
        `<strong>(${a}, ${b}, ${c})</strong> is not a Pythagorean triple: ${lo}&sup2; + ${hi}&sup2; = ${lo * lo + hi * hi}, not ${c * c}.`);
      return;
    }
    const tr = TRIPLES.find(t => t.a === lo && t.b === hi && t.c === c);
    if (tr) {
      setHighlightedIds(new Set([tr.id]));
      setDetailsId(tr.id);
      setPendingScroll({ type: 'card', id: tr.id });
      const kind = tr.primitive
        ? 'primitive'
        : `a multiple (k=${tr.k}) of (${tr.basePrim.a}, ${tr.basePrim.b}, ${tr.basePrim.c})`;
      setStatus('success', '\u2713',
        `<strong>(${a}, ${b}, ${c})</strong> is a Pythagorean triple, ${kind}. Card highlighted and details opened below.`);
    } else {
      setStatus('success', '\u2713',
        `<strong>(${a}, ${b}, ${c})</strong> is a Pythagorean triple, but outside this c &le; ${TABLE_MAX_C} table.`);
    }
  };

  // ===== Tool: Mode 2 (Find by leg) =====
  const runLeg = () => {
    const n = parseInt(legInput, 10);
    if (isNaN(n) || n < 1) {
      setStatus('error', '!', 'Please enter a positive integer.');
      return;
    }
    setActiveFilter(null);
    setDetailsId(null);

    const matches = TRIPLES.filter(t => t.a === n || t.b === n);
    const newSet = new Set(matches.map(t => t.id));
    setHighlightedIds(newSet);

    if (newSet.size === 0) {
      setStatus('info', '\u2211',
        `No triples with leg <strong>${n}</strong> in this c &le; ${TABLE_MAX_C} table.`);
    } else {
      setPendingScroll({ type: 'table' });
      setStatus('success', '\u2211',
        `<strong>${newSet.size}</strong> triple${newSet.size === 1 ? '' : 's'} contain ${n} as a leg. Highlighted below.`);
    }
  };

  // ===== Tool: Mode 3 (Find by hypotenuse) =====
  const runHyp = () => {
    const n = parseInt(hypInput, 10);
    if (isNaN(n) || n < 1) {
      setStatus('error', '!', 'Please enter a positive integer.');
      return;
    }
    setActiveFilter(null);
    setDetailsId(null);

    const matches = TRIPLES.filter(t => t.c === n);
    const newSet = new Set(matches.map(t => t.id));
    setHighlightedIds(newSet);

    if (newSet.size === 0) {
      setStatus('info', '\u2211',
        `No triples with hypotenuse <strong>${n}</strong> in this c &le; ${TABLE_MAX_C} table.`);
    } else {
      setPendingScroll({ type: 'table' });
      setStatus('success', '\u2211',
        `<strong>${newSet.size}</strong> triple${newSet.size === 1 ? '' : 's'} with hypotenuse ${n}. Highlighted below.`);
    }
  };

  // ===== Filter cards =====
  const toggleFilter = (id) => {
    setHighlightedIds(new Set());
    setDetailsId(null);
    if (activeFilter === id) {
      setActiveFilter(null);
      hideStatus();
    } else {
      setActiveFilter(id);
      hideStatus();
      setPendingScroll({ type: 'table' });
    }
  };

  const handleClearHighlights = () => {
    clearTableHighlights();
    hideStatus();
  };

  // ===== Card interaction =====
  const handleCardClick = (id) => {
    setDetailsId(id);
    setPendingScroll({ type: 'details' });
  };

  // ===== Derived =====
  const getCardClass = (t) => {
    let cls = 'ptp-triple-card';
    if (highlightedIds.has(t.id)) cls += ' highlight';
    if (activeFilter) {
      if (FILTER_SETS[activeFilter].has(t.id)) cls += ' filter-match';
      else cls += ' filter-dim';
    }
    return cls;
  };
  const getCardStyle = (t) => {
    const base = { ...S.tripleCardBase };
    if (!t.primitive) Object.assign(base, S.tripleCardMultipleBg);
    return base;
  };
  const getBadgeStyle = (t) => {
    const base = { ...S.tripleBadgeBase };
    if (t.primitive) {
      base.background = C.primaryLight;
      base.color = C.primaryDark;
    } else {
      base.background = '#e2e8f0';
      base.color = '#475569';
    }
    return base;
  };

  const tocLinkStyle = (id) => {
    const base = { ...S.tocLinkBase };
    if (activeSection === id) {
      base.color = C.primaryDark;
      base.borderLeftColor = C.primary;
      base.fontWeight = 600;
      base.background = `linear-gradient(90deg, ${C.primaryLight} 0%, transparent 100%)`;
    }
    return base;
  };
  const tocNumStyle = (id) => {
    const base = { ...S.tocNumBase };
    if (activeSection === id) {
      base.background = C.primary;
      base.color = 'white';
    }
    return base;
  };

  let bannerText = '';
  if (activeFilter) {
    const def = FILTER_DEFS.find((f) => f.id === activeFilter);
    const count = FILTER_SETS[activeFilter].size;
    bannerText = `Filtering: ${def.title} \u2014 ${count} match${count === 1 ? '' : 'es'} highlighted`;
  } else if (highlightedIds.size > 0) {
    bannerText = `${highlightedIds.size} triple${highlightedIds.size === 1 ? '' : 's'} highlighted by tool`;
  }
  const showBanner = activeFilter !== null || highlightedIds.size > 0;

  const detailsContent = (() => {
    if (detailsId === null) return null;
    const t = TRIPLES.find(x => x.id === detailsId);
    if (!t) return null;
    const area = (t.a * t.b) / 2;
    const perim = t.a + t.b + t.c;
    const inradius = (t.a + t.b - t.c) / 2;
    const props = [];
    if (t.primitive) props.push('Primitive');
    else props.push(`Multiple (k=${t.k})`);
    if (isPrime(t.c)) props.push('Prime hypotenuse');
    if (isPerfectSquare(t.a)) props.push(`Square leg (${t.a})`);
    if (isPerfectSquare(t.b)) props.push(`Square leg (${t.b})`);
    if (t.primitive && (t.m - t.n) === 1) props.push('Consecutive m, n');
    if (FILTER_SETS.family345.has(t.id)) props.push('(3,4,5) family');
    const generators = t.primitive
      ? `m = ${t.m}, n = ${t.n}`
      : `${t.k} \u00B7 (${t.basePrim.a}, ${t.basePrim.b}, ${t.basePrim.c})`;
    return { t, area, perim, inradius, props, generators };
  })();

  const statusIconBg = {
    success: C.success,
    error:   C.error,
    info:    C.primary,
  }[statusKind] || C.primary;

  const modeTabs = [
    { id: 'test', label: 'Is (a, b, c) a triple?' },
    { id: 'leg',  label: 'Find by leg' },
    { id: 'hyp',  label: 'Find by hypotenuse' },
  ];

  return (
    <>
      <style dangerouslySetInnerHTML={{ __html: CSS }} />
      <div style={S.container}>
        <div className="ptp-layout" style={S.pageLayout}>

          {/* ===== SIDEBAR (absolute, anchored to the container's left edge) ===== */}
          <aside className="ptp-sidebar" style={S.sidebar}>
            <div className="ptp-sidebar-sticky" style={S.sidebarSticky}>
              <div style={S.sidebarBlock}>
                <div style={S.sidebarLabel}>On this page</div>
                <ul style={S.tocList}>
                  {TOC_ITEMS.map((item, idx) => (
                    <li key={item.id}>
                      <a
                        className={`ptp-toc-link ${activeSection === item.id ? 'active' : ''}`}
                        style={tocLinkStyle(item.id)}
                        onClick={(e) => {
                          e.preventDefault();
                          const t = sectionRefs.current[item.id];
                          if (t) t.scrollIntoView({ behavior: 'smooth', block: 'start' });
                        }}
                      >
                        <span style={tocNumStyle(item.id)}>{idx + 1}</span>
                        {item.label}
                      </a>
                    </li>
                  ))}
                </ul>
              </div>

              {relatedReferences && relatedReferences.length > 0 && (
                <div style={S.sidebarBlock}>
                  <div style={S.sidebarLabel}>Related references</div>
                  {relatedReferences.map((ref, idx) => (
                    <a
                      key={idx}
                      href={ref.href}
                      className="ptp-related-mini"
                      style={S.relatedMini}
                    >
                      <div style={S.relatedMiniTitle}>{ref.title}</div>
                      {ref.sub && <div style={S.relatedMiniSub}>{ref.sub}</div>}
                    </a>
                  ))}
                </div>
              )}
            </div>
          </aside>

          {/* ===== MAIN ===== */}
          <div style={S.mainCol}>

            {/* TOOL */}
            <section
              id="sec-tool"
              ref={(el) => { sectionRefs.current['sec-tool'] = el; }}
              style={S.toolSection}
            >
              <div style={S.toolHeader}>
                <h2 style={S.toolH2}>Pythagorean Triple Tool</h2>
                <p style={S.toolSub}>Every answer takes you to the table. Pick a question:</p>
              </div>

              <div style={S.modeTabsWrap} role="tablist">
                {modeTabs.map((tab) => {
                  const isActive = mode === tab.id;
                  return (
                    <button
                      key={tab.id}
                      type="button"
                      className={`ptp-mode-tab ${isActive ? 'active' : ''}`}
                      style={{ ...S.modeTabBase, ...(isActive ? S.modeTabActive : {}) }}
                      onClick={() => handleModeChange(tab.id)}
                    >
                      {tab.label}
                    </button>
                  );
                })}
              </div>

              {mode === 'test' && (
                <div className="ptp-input-block" style={S.inputBlock}>
                  <input
                    type="number"
                    className="ptp-input-field"
                    style={{ ...S.inputField, ...S.inputFieldNarrow }}
                    placeholder="a"
                    min="1"
                    value={aInput}
                    onChange={(e) => setAInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') runTest(); }}
                  />
                  <input
                    type="number"
                    className="ptp-input-field"
                    style={{ ...S.inputField, ...S.inputFieldNarrow }}
                    placeholder="b"
                    min="1"
                    value={bInput}
                    onChange={(e) => setBInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') runTest(); }}
                  />
                  <input
                    type="number"
                    className="ptp-input-field"
                    style={{ ...S.inputField, ...S.inputFieldNarrow }}
                    placeholder="c"
                    min="1"
                    value={cInput}
                    onChange={(e) => setCInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') runTest(); }}
                  />
                  <button
                    type="button"
                    className="ptp-input-btn"
                    style={S.inputBtn}
                    onClick={runTest}
                  >
                    Test
                  </button>
                </div>
              )}

              {mode === 'leg' && (
                <div className="ptp-input-block" style={S.inputBlock}>
                  <input
                    type="number"
                    className="ptp-input-field"
                    style={S.inputField}
                    placeholder="Enter a leg (e.g., 12)"
                    min="1"
                    value={legInput}
                    onChange={(e) => setLegInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') runLeg(); }}
                  />
                  <button
                    type="button"
                    className="ptp-input-btn"
                    style={S.inputBtn}
                    onClick={runLeg}
                  >
                    Find
                  </button>
                </div>
              )}

              {mode === 'hyp' && (
                <div className="ptp-input-block" style={S.inputBlock}>
                  <input
                    type="number"
                    className="ptp-input-field"
                    style={S.inputField}
                    placeholder="Enter a hypotenuse (e.g., 65)"
                    min="1"
                    value={hypInput}
                    onChange={(e) => setHypInput(e.target.value)}
                    onKeyDown={(e) => { if (e.key === 'Enter') runHyp(); }}
                  />
                  <button
                    type="button"
                    className="ptp-input-btn"
                    style={S.inputBtn}
                    onClick={runHyp}
                  >
                    Find
                  </button>
                </div>
              )}

              {statusKind && (
                <div style={S.toolStatus}>
                  <span style={{ ...S.statusIcon, background: statusIconBg }}>{statusIcon}</span>
                  <span dangerouslySetInnerHTML={{ __html: statusHtml }} />
                </div>
              )}
            </section>

            {/* TABLE */}
            <section
              id="sec-table"
              ref={(el) => { sectionRefs.current['sec-table'] = el; }}
            >
              <div style={S.legend}>
                <div style={S.legendTitle}>Card types</div>
                <div style={S.legendRow}>
                  {LEGEND_PILLS.map((p, i) => {
                    const st = PILL_STYLES[p.kind];
                    return (
                      <span
                        key={i}
                        style={{ ...S.legendPillBase, background: st.bg, color: st.fg }}
                      >
                        {p.label}
                      </span>
                    );
                  })}
                </div>
                <p style={S.legendNote}>
                  A triple (a, b, c) satisfies a&sup2; + b&sup2; = c&sup2;. It&apos;s <strong>primitive</strong> when gcd(a, b, c) = 1; every other triple is k&middot;(a, b, c) for some primitive. Showing all triples with c &le; {TABLE_MAX_C}.
                </p>
              </div>

              {showBanner && (
                <div style={S.filterStatus}>
                  <span style={S.filterStatusText}>{bannerText}</span>
                  <button
                    type="button"
                    style={S.filterClear}
                    onClick={handleClearHighlights}
                  >
                    Clear highlight
                  </button>
                </div>
              )}

              <div className="ptp-triple-grid" style={S.tripleGrid}>
                {TRIPLES.map((t) => {
                  const meta = t.primitive
                    ? `m=${t.m}, n=${t.n}`
                    : `${t.k}\u00B7(${t.basePrim.a}, ${t.basePrim.b}, ${t.basePrim.c})`;
                  return (
                    <div
                      key={t.id}
                      ref={(el) => { cardRefs.current[t.id] = el; }}
                      className={getCardClass(t)}
                      style={getCardStyle(t)}
                      onClick={() => handleCardClick(t.id)}
                    >
                      <span style={getBadgeStyle(t)}>
                        {t.primitive ? 'Primitive' : `\u00D7${t.k}`}
                      </span>
                      <div style={S.tripleSvgWrap}>
                        <TripleSvg a={t.a} b={t.b} primitive={t.primitive} />
                      </div>
                      <div style={S.tripleValues}>{t.a}, {t.b}, {t.c}</div>
                      <div style={S.tripleMeta}>{meta}</div>
                    </div>
                  );
                })}
              </div>

              {detailsContent && (
                <div id="ptp-cell-details" className="ptp-cell-details" style={S.cellDetails}>
                  <button
                    type="button"
                    className="ptp-close-details"
                    style={S.closeDetails}
                    onClick={() => setDetailsId(null)}
                  >
                    &times;
                  </button>
                  <h3 style={S.detailsH3}>
                    {detailsContent.t.a}<sup>2</sup> + {detailsContent.t.b}<sup>2</sup> = {detailsContent.t.c}<sup>2</sup>
                  </h3>
                  <div style={S.detailGrid}>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Legs and hypotenuse</div>
                      <div style={S.detailValue}>
                        {detailsContent.t.a}, {detailsContent.t.b}, {detailsContent.t.c}
                      </div>
                    </div>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Check</div>
                      <div style={S.detailValue}>
                        {detailsContent.t.a * detailsContent.t.a} + {detailsContent.t.b * detailsContent.t.b} = {detailsContent.t.c * detailsContent.t.c}
                      </div>
                    </div>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Generators</div>
                      <div style={S.detailValue}>{detailsContent.generators}</div>
                    </div>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Area</div>
                      <div style={S.detailValue}>{detailsContent.area}</div>
                    </div>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Perimeter</div>
                      <div style={S.detailValue}>{detailsContent.perim}</div>
                    </div>
                    <div style={S.detailItem}>
                      <div style={S.detailLabel}>Inradius</div>
                      <div style={S.detailValue}>{detailsContent.inradius}</div>
                    </div>
                    {detailsContent.props.length > 0 && (
                      <div style={{ ...S.detailItem, gridColumn: '1 / -1' }}>
                        <div style={S.detailLabel}>Properties</div>
                        <div style={S.propertyBadges}>
                          {detailsContent.props.map((p, i) => (
                            <span key={i} style={S.badge}>{p}</span>
                          ))}
                        </div>
                      </div>
                    )}
                  </div>
                </div>
              )}
            </section>

            {/* PATTERNS */}
            <section
              id="sec-patterns"
              ref={(el) => { sectionRefs.current['sec-patterns'] = el; }}
            >
              <h2 style={S.sectionH}>Patterns to explore</h2>
              <p style={S.sectionSub}>Click a card to highlight every matching triple in the table above.</p>
              <div style={S.filterGrid}>
                {FILTER_DEFS.map((f) => {
                  const isActive = activeFilter === f.id;
                  return (
                    <div
                      key={f.id}
                      className={`ptp-filter-card ${isActive ? 'active' : ''}`}
                      style={S.filterCard}
                      onClick={() => toggleFilter(f.id)}
                    >
                      <div className="ptp-filter-icon" style={S.filterIcon}>{f.icon}</div>
                      <h3 style={S.filterCardH3}>{f.title}</h3>
                      <p style={S.filterCardP}>{f.desc}</p>
                      <div style={S.filterCardFooter}>
                        <span className="ptp-filter-count" style={S.filterCount}>{FILTER_SETS[f.id].size} match{FILTER_SETS[f.id].size === 1 ? '' : 'es'}</span>
                        <span className="ptp-filter-action" style={S.filterAction}>Click to highlight</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>

            {/* PROPERTIES */}
            <section
              id="sec-properties"
              ref={(el) => { sectionRefs.current['sec-properties'] = el; }}
              style={S.propertiesSection}
            >
              <h2 style={S.sectionH}>Properties of Pythagorean triples</h2>
              <p style={S.sectionSub}>Facts true of every primitive triple &mdash; useful for spotting them and ruling them out.</p>
              <div style={S.propertyGrid}>
                {PROPERTY_CARDS.map((card, i) => (
                  <div key={i} style={S.propertyCard}>
                    <div style={S.propertyCardIcon}>{card.icon}</div>
                    <h4 style={S.propertyCardH4}>{card.title}</h4>
                    <p
                      style={S.propertyCardP}
                      dangerouslySetInnerHTML={{ __html: card.body }}
                    />
                    {card.code && (
                      <code
                        style={S.propertyCardCode}
                        dangerouslySetInnerHTML={{ __html: card.code }}
                      />
                    )}
                    {card.hasMnGrid && <MnGrid />}
                  </div>
                ))}
              </div>
            </section>

            {/* QUIZ */}
            <section
              id="sec-quiz"
              ref={(el) => { sectionRefs.current['sec-quiz'] = el; }}
              style={S.quizSection}
            >
              <QuizWidget
                generator={generatePythagoreanTripleQuestion}
                title="Test yourself"
                subtitle="Three question types, rotated at random."
                allowReset={true}
                historyLimit={30}
              />
            </section>
          </div>
        </div>
      </div>
    </>
  );
};

export default PythagoreanTriplesPage;