// Navigation Menu Color Themes
// Import this file and pass theme to MyNavbar3 component

const navThemes = {
  // Theme #1 - White (DEFAULT)
  white: {
    id: 'white',
    name: 'White',
    panelBackground: '#ffffff',
    panelBorder: '#e5e7eb',
    itemBackground: '#ffffff',
    itemText: '#1f2937',
    itemHoverBackground: '#f3f4f6',
    itemHoverBorderColor: '#4d4dff',
    itemHoverText: '#4d4dff',
    sectionBorder: '#4d4dff',
    sectionTitleText: '#1f2937',
    sectionTitleHoverText: '#4d4dff',
  },

  // Theme #4 - Dark
  dark: {
    id: 'dark',
    name: 'Dark',
    panelBackground: '#2d3748',
    panelBorder: '#4a5568',
    itemBackground: '#2d3748',
    itemText: '#e2e8f0',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#6d6dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#ffffff',
    sectionTitleText: '#e2e8f0',
    sectionTitleHoverText: '#6d6dff',
  },

  // Theme #5 - Lighter Dark
  lighterDark: {
    id: 'lighterDark',
    name: 'Lighter Dark',
    panelBackground: '#4a5568',
    panelBorder: '#718096',
    itemBackground: '#2d3748',
    itemText: '#e2e8f0',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#6d6dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#6d6dff',
    sectionTitleText: '#e2e8f0',
    sectionTitleHoverText: '#8d8dff',
  },

  // Theme #8 - Darker Medium Gray
  mediumGray: {
    id: 'mediumGray',
    name: 'Medium Gray',
    panelBackground: '#8c8c8c',
    panelBorder: '#a6a6a6',
    itemBackground: '#e8e8e8',
    itemText: '#1f2937',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#2929cc',
    itemHoverText: '#ffffff',
    sectionBorder: '#5d5dff',
    sectionTitleText: '#1f2937',
    sectionTitleHoverText: '#4d4dff',
  },

  // Theme #9 - Cool Blue-Gray (RECOMMENDED)
  coolBlueGray: {
    id: 'coolBlueGray',
    name: 'Cool Blue-Gray',
    panelBackground: '#8a92a6',
    panelBorder: '#a0a8bb',
    itemBackground: '#b8bfcf',
    itemText: '#1f2937',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#2929cc',
    itemHoverText: '#ffffff',
    sectionBorder: '#5d5dff',
    sectionTitleText: '#1f2937',
    sectionTitleHoverText: '#4d4dff',
  },
   slatePro: {
    id: 'slatePro',
    name: 'Slate Professional',
    panelBackground: '#f8fafc',
    panelBorder: '#cbd5e1',
    itemBackground: '#ffffff',
    itemText: '#334155',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#4d4dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#cbd5e1',
    sectionTitleText: '#0f172a',
    sectionTitleHoverText: '#4d4dff',
  },

   warmBeige: {
    id: 'warmBeige',
    name: 'Warm Beige',
    panelBackground: '#faf8f5',
    panelBorder: '#e7e0d5',
    itemBackground: '#ffffff',
    itemText: '#3e3226',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#4d4dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#d4c5b0',
    sectionTitleText: '#2d2419',
    sectionTitleHoverText: '#4d4dff',
  },
  midnightBlue: {
    id: 'midnightBlue',
    name: 'Midnight Blue',
    panelBackground: '#1e293b',
    panelBorder: '#334155',
    itemBackground: '#1e293b',
    itemText: '#cbd5e1',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#6d6dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#475569',
    sectionTitleText: '#f1f5f9',
    sectionTitleHoverText: '#8d8dff',
  },

  // Theme #7 - Soft Purple
  softPurple: {
    id: 'softPurple',
    name: 'Soft Purple',
    panelBackground: '#faf5ff',
    panelBorder: '#e9d5ff',
    itemBackground: '#ffffff',
    itemText: '#581c87',
    itemHoverBackground: '#7c3aed',
    itemHoverBorderColor: '#7c3aed',
    itemHoverText: '#ffffff',
    sectionBorder: '#d8b4fe',
    sectionTitleText: '#4c1d95',
    sectionTitleHoverText: '#7c3aed',
  },
   coolBlueGray: {
    id: 'coolBlueGray',
    name: 'Cool Blue-Gray',
    panelBackground: '#8a92a6',
    panelBorder: '#a0a8bb',
    itemBackground: '#b8bfcf',
    itemText: '#1f2937',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#2929cc',
    itemHoverText: '#ffffff',
    sectionBorder: '#5d5dff',
    sectionTitleText: '#1f2937',
    sectionTitleHoverText: '#4d4dff',
  },

  // Theme #10 - Ocean Teal
  oceanTeal: {
    id: 'oceanTeal',
    name: 'Ocean Teal',
    panelBackground: '#f0fdfa',
    panelBorder: '#99f6e4',
    itemBackground: '#ffffff',
    itemText: '#115e59',
    itemHoverBackground: '#14b8a6',
    itemHoverBorderColor: '#14b8a6',
    itemHoverText: '#ffffff',
    sectionBorder: '#5eead4',
    sectionTitleText: '#134e4a',
    sectionTitleHoverText: '#14b8a6',
  },

  // Theme #11 - Emerald Fresh
  emeraldFresh: {
    id: 'emeraldFresh',
    name: 'Emerald Fresh',
    panelBackground: '#f0fdf4',
    panelBorder: '#bbf7d0',
    itemBackground: '#ffffff',
    itemText: '#14532d',
    itemHoverBackground: '#10b981',
    itemHoverBorderColor: '#10b981',
    itemHoverText: '#ffffff',
    sectionBorder: '#86efac',
    sectionTitleText: '#052e16',
    sectionTitleHoverText: '#10b981',
  },

  // Theme #12 - Amber Warmth
  amberWarm: {
    id: 'amberWarm',
    name: 'Amber Warmth',
    panelBackground: '#fffbeb',
    panelBorder: '#fde68a',
    itemBackground: '#ffffff',
    itemText: '#78350f',
    itemHoverBackground: '#f59e0b',
    itemHoverBorderColor: '#f59e0b',
    itemHoverText: '#ffffff',
    sectionBorder: '#fcd34d',
    sectionTitleText: '#451a03',
    sectionTitleHoverText: '#f59e0b',
  },

  // Theme #13 - Rose Elegant
  roseElegant: {
    id: 'roseElegant',
    name: 'Rose Elegant',
    panelBackground: '#fff1f2',
    panelBorder: '#fecdd3',
    itemBackground: '#ffffff',
    itemText: '#881337',
    itemHoverBackground: '#e11d48',
    itemHoverBorderColor: '#e11d48',
    itemHoverText: '#ffffff',
    sectionBorder: '#fda4af',
    sectionTitleText: '#4c0519',
    sectionTitleHoverText: '#e11d48',
  },

  // Theme #14 - Indigo Deep
  indigoDeep: {
    id: 'indigoDeep',
    name: 'Indigo Deep',
    panelBackground: '#eef2ff',
    panelBorder: '#c7d2fe',
    itemBackground: '#ffffff',
    itemText: '#3730a3',
    itemHoverBackground: '#6366f1',
    itemHoverBorderColor: '#6366f1',
    itemHoverText: '#ffffff',
    sectionBorder: '#a5b4fc',
    sectionTitleText: '#1e1b4b',
    sectionTitleHoverText: '#6366f1',
  },

  // Theme #15 - Charcoal Modern
  charcoalModern: {
    id: 'charcoalModern',
    name: 'Charcoal Modern',
    panelBackground: '#3f3f46',
    panelBorder: '#52525b',
    itemBackground: '#27272a',
    itemText: '#e4e4e7',
    itemHoverBackground: '#4d4dff',
    itemHoverBorderColor: '#6d6dff',
    itemHoverText: '#ffffff',
    sectionBorder: '#71717a',
    sectionTitleText: '#fafafa',
    sectionTitleHoverText: '#8d8dff',
  },

  // Theme #16 - Minimal Contrast
  minimalContrast: {
    id: 'minimalContrast',
    name: 'Minimal Contrast',
    panelBackground: '#fafafa',
    panelBorder: '#e5e5e5',
    itemBackground: '#ffffff',
    itemText: '#262626',
    itemHoverBackground: '#171717',
    itemHoverBorderColor: '#171717',
    itemHoverText: '#ffffff',
    sectionBorder: '#d4d4d4',
    sectionTitleText: '#0a0a0a',
    sectionTitleHoverText: '#404040',
  },

  // Theme #17 - Sky Light
  skyLight: {
    id: 'skyLight',
    name: 'Sky Light',
    panelBackground: '#f0f9ff',
    panelBorder: '#bae6fd',
    itemBackground: '#ffffff',
    itemText: '#0c4a6e',
    itemHoverBackground: '#0ea5e9',
    itemHoverBorderColor: '#0ea5e9',
    itemHoverText: '#ffffff',
    sectionBorder: '#7dd3fc',
    sectionTitleText: '#082f49',
    sectionTitleHoverText: '#0ea5e9',
  },
};

export default navThemes;