// /functions/visual-tools/diagrams — the gallery of every diagram already
// placed on the functions pages. Listed by the /functions/visual-tools hub
// through the `category: "Diagrams"` it declares below (buildToolIndexData
// scans this file's seoData). Data: app/api/db/repositories/diagrams/functions.json,
// generated by `node scripts/build-diagrams.mjs --subject=functions`.
import Breadcrumb from '@/app/components/breadcrumb/Breadcrumb'
import OperaSidebar from '@/app/components/nav-bar/OperaSidebar'
import React from 'react'
import '@/pages/pages.css'
import Head from 'next/head'
import DiagramsExplorer from '@/app/components/diagrams-explorer/DiagramsExplorer'
import diagrams from '@/app/api/db/repositories/diagrams/functions.json'

export async function getStaticProps() {
  const keyWords = [
    'functions diagrams',
    'functions illustrations',
    'function graph diagram',
    'domain and range diagram',
    'inverse function diagram',
    'function transformations diagram',
    'composition of functions diagram',
    'functions visual tools',
    'learn functions visually',
  ]
  const schemas = {
    webPage: {
      '@context': 'https://schema.org',
      '@type': 'CollectionPage',
      name: 'Functions Diagrams',
      description: 'Every diagram on the functions pages in one gallery, each linked to the section it illustrates.',
      url: 'https://www.learnmathclass.com/functions/visual-tools/diagrams',
    },
    breadcrumb: {
      '@context': 'https://schema.org',
      '@type': 'BreadcrumbList',
      itemListElement: [
        { '@type': 'ListItem', position: 1, name: 'Home', item: 'https://www.learnmathclass.com' },
        { '@type': 'ListItem', position: 2, name: 'Functions', item: 'https://www.learnmathclass.com/functions' },
        { '@type': 'ListItem', position: 3, name: 'Visual Tools', item: 'https://www.learnmathclass.com/functions/visual-tools' },
        { '@type': 'ListItem', position: 4, name: 'Diagrams', item: 'https://www.learnmathclass.com/functions/visual-tools/diagrams' },
      ],
    },
  }
  return {
    props: {
      diagrams,
      schemas,
      seoData: {
        title: 'Functions Diagrams: Every Figure on the Functions Pages | Learn Math Class',
        description: 'Browse every functions diagram in one gallery: graphs, domain and range, transformations, inverses and compositions, each linked to the exact section it illustrates and to the tool that drew it.',
        hubDescription: 'A gallery of every diagram already shown on the functions pages: figures drawn for the lessons and frozen states of the visual tools. Browse by chapter or page, search captions, compare two figures side by side, and jump from any picture to the exact section where it appears or to the tool that drew it.',
        category: 'Diagrams',
        keywords: keyWords.join(', '),
        url: '/functions/visual-tools/diagrams',
        svg: `<svg viewBox="0 0 80 80" xmlns="http://www.w3.org/2000/svg"><rect x="8" y="10" width="28" height="22" rx="3" fill="#E6F1FB" stroke="#185FA5" stroke-width="1.2"/><rect x="44" y="10" width="28" height="22" rx="3" fill="#FAC775" stroke="#854F0B" stroke-width="1.2"/><rect x="8" y="40" width="28" height="22" rx="3" fill="#FAC775" stroke="#854F0B" stroke-width="1.2"/><rect x="44" y="40" width="28" height="22" rx="3" fill="#E6F1FB" stroke="#185FA5" stroke-width="1.2"/><path d="M12 28 L22 16 L32 28" fill="none" stroke="#185FA5" stroke-width="1.6"/><circle cx="58" cy="21" r="7" fill="none" stroke="#854F0B" stroke-width="1.6"/><path d="M58 21 L64 17" stroke="#854F0B" stroke-width="1.6"/><path d="M12 56 Q22 42 32 56" fill="none" stroke="#854F0B" stroke-width="1.6"/><path d="M48 58 L58 44 L68 58 Z" fill="none" stroke="#185FA5" stroke-width="1.6"/><text x="40" y="74" font-family="Georgia,serif" font-size="7" fill="#042C53" text-anchor="middle">diagrams</text></svg>`,
        name: 'Functions Diagrams',
      },
    },
  }
}

export default function FunctionsDiagramsPage({ diagrams, seoData, schemas }) {
  return (
    <>
      <Head>
        <title>{seoData.title}</title>
        <meta name="description" content={seoData.description} />
        <meta name="keywords" content={seoData.keywords} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="canonical" href={`https://www.learnmathclass.com${seoData.url}`} />
        <meta property="og:title" content={seoData.title} />
        <meta property="og:description" content={seoData.description} />
        <meta property="og:url" content={`https://www.learnmathclass.com${seoData.url}`} />
        <meta property="og:type" content="article" />
        <meta property="og:site_name" content="Learn Math Class" />
        <meta name="twitter:card" content="summary" />
        <meta name="twitter:title" content={seoData.title} />
        <meta name="twitter:description" content={seoData.description} />
        <meta name="robots" content="index, follow" />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas.webPage) }} />
        <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schemas.breadcrumb) }} />
      </Head>
      <br />
      <br />
      <br />
      <br />
      <OperaSidebar
        side='right'
        sidebarWidth='45px'
        panelWidth='200px'
        iconColor='white'
        panelBackgroundColor='#f2f2f2'
      />
      <Breadcrumb />
      <br />
      <br />
      <h1 className='title' style={{ marginTop: '-20px', marginBottom: '10px' }}>Functions Diagrams</h1>
      <DiagramsExplorer data={diagrams} subjectLabel="Functions" />
      <br />
      <br />
    </>
  )
}
