// themes.js
// Drop-in palettes for TablePuzzle.
//
// Usage:
//   import TablePuzzle from './TablePuzzle';
//   import { TEAL_THEME } from './themes';
//   <TablePuzzle theme={TEAL_THEME} />
//
// Or pick by name:
//   import { THEMES } from './themes';
//   <TablePuzzle theme={THEMES.periwinkle} />

/* ============================================================
   SKY — bright modern blue (default)
   ============================================================ */
export const SKY_THEME = {
  name: 'sky',
  light: {
    '--bg': '#f0f7ff',
    '--text': '#0f2849',
    '--muted': '#64748b',
    '--board': '#dceaf8',
    '--header-bg': '#c5dcf2',
    '--header-text': '#0f2849',
    '--cell': '#ffffff',
    '--tile': '#3b82f6',
    '--tile-hover': '#2563eb',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#eaf3fd',
    '--tile-correct-border': '#1e40af',
    '--tile-correct-text': '#0f2849',
    '--success-bg': '#1e40af',
    '--success-text': '#ffffff',
    '--success-link': '#bfdbfe',
    '--accent': '#2563eb',
    '--accent-soft': '#dbeafe',
    '--btn': '#2563eb',
    '--btn-hover': '#1d4ed8',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#dceaf8',
    '--btn-secondary-hover': '#bfdbfe',
    '--btn-secondary-text': '#0f2849',
    '--win': '#1e40af',
    '--win-glow': 'rgba(59, 130, 246, 0.45)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(15, 40, 73, 0.18)',
    '--tip-bg': '#0f172a',
    '--tip-text': '#f1f5f9',
    '--tip-border': '#334155',
    '--tip-shadow': 'rgba(0, 0, 0, 0.35)',
    '--tip-link': '#93c5fd',
    '--tip-muted': '#94a3b8',
  },
  dark: {
    '--bg': '#0f1729',
    '--text': '#dbeafe',
    '--muted': '#94a3b8',
    '--board': '#1e293b',
    '--header-bg': '#334155',
    '--header-text': '#dbeafe',
    '--cell': '#1e293b',
    '--tile': '#3b82f6',
    '--tile-hover': '#2563eb',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#1a2a4d',
    '--tile-correct-border': '#60a5fa',
    '--tile-correct-text': '#dbeafe',
    '--success-bg': '#1d4ed8',
    '--success-text': '#ffffff',
    '--success-link': '#bfdbfe',
    '--accent': '#60a5fa',
    '--accent-soft': '#1e3a5f',
    '--btn': '#2563eb',
    '--btn-hover': '#3b82f6',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#334155',
    '--btn-secondary-hover': '#475569',
    '--btn-secondary-text': '#dbeafe',
    '--win': '#60a5fa',
    '--win-glow': 'rgba(96, 165, 250, 0.5)',
    '--banner-bg': '#1e293b',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#0a0f1e',
    '--tip-text': '#f1f5f9',
    '--tip-border': '#334155',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#93c5fd',
    '--tip-muted': '#94a3b8',
  },
};

/* ============================================================
   PERIWINKLE — soft indigo
   ============================================================ */
export const PERIWINKLE_THEME = {
  name: 'periwinkle',
  light: {
    '--bg': '#f5f6fc',
    '--text': '#1e1b4b',
    '--muted': '#64748b',
    '--board': '#e0e2f4',
    '--header-bg': '#c7cbec',
    '--header-text': '#1e1b4b',
    '--cell': '#ffffff',
    '--tile': '#6366f1',
    '--tile-hover': '#4f46e5',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#ecedfb',
    '--tile-correct-border': '#3730a3',
    '--tile-correct-text': '#1e1b4b',
    '--success-bg': '#3730a3',
    '--success-text': '#ffffff',
    '--success-link': '#c7d2fe',
    '--accent': '#4f46e5',
    '--accent-soft': '#e0e7ff',
    '--btn': '#4f46e5',
    '--btn-hover': '#4338ca',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#e0e2f4',
    '--btn-secondary-hover': '#c7cbec',
    '--btn-secondary-text': '#1e1b4b',
    '--win': '#3730a3',
    '--win-glow': 'rgba(99, 102, 241, 0.45)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(30, 27, 75, 0.2)',
    '--tip-bg': '#1e1b4b',
    '--tip-text': '#ede9fe',
    '--tip-border': '#3730a3',
    '--tip-shadow': 'rgba(0, 0, 0, 0.4)',
    '--tip-link': '#c7d2fe',
    '--tip-muted': '#a5b4fc',
  },
  dark: {
    '--bg': '#1a1530',
    '--text': '#ede9fe',
    '--muted': '#a5b4fc',
    '--board': '#2a2350',
    '--header-bg': '#3a3070',
    '--header-text': '#ede9fe',
    '--cell': '#2a2350',
    '--tile': '#818cf8',
    '--tile-hover': '#6366f1',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#231d40',
    '--tile-correct-border': '#a5b4fc',
    '--tile-correct-text': '#ede9fe',
    '--success-bg': '#4338ca',
    '--success-text': '#ffffff',
    '--success-link': '#c7d2fe',
    '--accent': '#a5b4fc',
    '--accent-soft': '#2e2860',
    '--btn': '#6366f1',
    '--btn-hover': '#818cf8',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#3a3070',
    '--btn-secondary-hover': '#4c3e90',
    '--btn-secondary-text': '#ede9fe',
    '--win': '#a5b4fc',
    '--win-glow': 'rgba(165, 180, 252, 0.5)',
    '--banner-bg': '#2a2350',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#0f0a26',
    '--tip-text': '#ede9fe',
    '--tip-border': '#3a3070',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#c7d2fe',
    '--tip-muted': '#a5b4fc',
  },
};

/* ============================================================
   TEAL — cool, fresh, cyan-leaning
   ============================================================ */
export const TEAL_THEME = {
  name: 'teal',
  light: {
    '--bg': '#f0fafa',
    '--text': '#134e4a',
    '--muted': '#64748b',
    '--board': '#d9eef1',
    '--header-bg': '#b8dde2',
    '--header-text': '#134e4a',
    '--cell': '#ffffff',
    '--tile': '#0891b2',
    '--tile-hover': '#0e7490',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#e6f4f7',
    '--tile-correct-border': '#155e75',
    '--tile-correct-text': '#134e4a',
    '--success-bg': '#155e75',
    '--success-text': '#ffffff',
    '--success-link': '#a5f3fc',
    '--accent': '#0e7490',
    '--accent-soft': '#cffafe',
    '--btn': '#0e7490',
    '--btn-hover': '#155e75',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#d9eef1',
    '--btn-secondary-hover': '#b8dde2',
    '--btn-secondary-text': '#134e4a',
    '--win': '#155e75',
    '--win-glow': 'rgba(8, 145, 178, 0.45)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(19, 78, 74, 0.18)',
    '--tip-bg': '#042f2e',
    '--tip-text': '#ecfeff',
    '--tip-border': '#134e4a',
    '--tip-shadow': 'rgba(0, 0, 0, 0.35)',
    '--tip-link': '#a5f3fc',
    '--tip-muted': '#67e8f9',
  },
  dark: {
    '--bg': '#0a2425',
    '--text': '#cffafe',
    '--muted': '#67e8f9',
    '--board': '#1a3940',
    '--header-bg': '#2a5560',
    '--header-text': '#cffafe',
    '--cell': '#1a3940',
    '--tile': '#06b6d4',
    '--tile-hover': '#0891b2',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#143a44',
    '--tile-correct-border': '#67e8f9',
    '--tile-correct-text': '#cffafe',
    '--success-bg': '#0e7490',
    '--success-text': '#ffffff',
    '--success-link': '#a5f3fc',
    '--accent': '#67e8f9',
    '--accent-soft': '#143a44',
    '--btn': '#0891b2',
    '--btn-hover': '#06b6d4',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#2a5560',
    '--btn-secondary-hover': '#3a6b78',
    '--btn-secondary-text': '#cffafe',
    '--win': '#67e8f9',
    '--win-glow': 'rgba(103, 232, 249, 0.5)',
    '--banner-bg': '#1a3940',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#04181a',
    '--tip-text': '#ecfeff',
    '--tip-border': '#155e75',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#a5f3fc',
    '--tip-muted': '#67e8f9',
  },
};

/* ============================================================
   SLATE — neutral gray with blue accent
   ============================================================ */
export const SLATE_THEME = {
  name: 'slate',
  light: {
    '--bg': '#f6f7fa',
    '--text': '#1e293b',
    '--muted': '#64748b',
    '--board': '#e2e8f0',
    '--header-bg': '#cbd5e1',
    '--header-text': '#1e293b',
    '--cell': '#ffffff',
    '--tile': '#475569',
    '--tile-hover': '#334155',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#f1f5f9',
    '--tile-correct-border': '#1e293b',
    '--tile-correct-text': '#1e293b',
    '--success-bg': '#334155',
    '--success-text': '#ffffff',
    '--success-link': '#cbd5e1',
    '--accent': '#334155',
    '--accent-soft': '#e2e8f0',
    '--btn': '#334155',
    '--btn-hover': '#1e293b',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#e2e8f0',
    '--btn-secondary-hover': '#cbd5e1',
    '--btn-secondary-text': '#1e293b',
    '--win': '#334155',
    '--win-glow': 'rgba(71, 85, 105, 0.45)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(30, 41, 59, 0.18)',
    '--tip-bg': '#0f172a',
    '--tip-text': '#f1f5f9',
    '--tip-border': '#334155',
    '--tip-shadow': 'rgba(0, 0, 0, 0.35)',
    '--tip-link': '#cbd5e1',
    '--tip-muted': '#94a3b8',
  },
  dark: {
    '--bg': '#0f172a',
    '--text': '#e2e8f0',
    '--muted': '#94a3b8',
    '--board': '#1e293b',
    '--header-bg': '#334155',
    '--header-text': '#e2e8f0',
    '--cell': '#1e293b',
    '--tile': '#64748b',
    '--tile-hover': '#475569',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#1e2535',
    '--tile-correct-border': '#cbd5e1',
    '--tile-correct-text': '#e2e8f0',
    '--success-bg': '#475569',
    '--success-text': '#ffffff',
    '--success-link': '#cbd5e1',
    '--accent': '#cbd5e1',
    '--accent-soft': '#334155',
    '--btn': '#475569',
    '--btn-hover': '#64748b',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#334155',
    '--btn-secondary-hover': '#475569',
    '--btn-secondary-text': '#e2e8f0',
    '--win': '#cbd5e1',
    '--win-glow': 'rgba(203, 213, 225, 0.5)',
    '--banner-bg': '#1e293b',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#020617',
    '--tip-text': '#f1f5f9',
    '--tip-border': '#334155',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#cbd5e1',
    '--tip-muted': '#94a3b8',
  },
};

/* ============================================================
   AZURE — lighter, more saturated royal blue
   ============================================================ */
export const AZURE_THEME = {
  name: 'azure',
  light: {
    '--bg': '#eff6ff',
    '--text': '#1e3a8a',
    '--muted': '#64748b',
    '--board': '#dbeafe',
    '--header-bg': '#bfdbfe',
    '--header-text': '#1e3a8a',
    '--cell': '#ffffff',
    '--tile': '#60a5fa',
    '--tile-hover': '#3b82f6',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#eaf3fd',
    '--tile-correct-border': '#1e3a8a',
    '--tile-correct-text': '#1e3a8a',
    '--success-bg': '#1d4ed8',
    '--success-text': '#ffffff',
    '--success-link': '#bfdbfe',
    '--accent': '#2563eb',
    '--accent-soft': '#dbeafe',
    '--btn': '#2563eb',
    '--btn-hover': '#1d4ed8',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#dbeafe',
    '--btn-secondary-hover': '#bfdbfe',
    '--btn-secondary-text': '#1e3a8a',
    '--win': '#1e3a8a',
    '--win-glow': 'rgba(96, 165, 250, 0.5)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(30, 58, 138, 0.2)',
    '--tip-bg': '#0c1a3a',
    '--tip-text': '#dbeafe',
    '--tip-border': '#1e3a8a',
    '--tip-shadow': 'rgba(0, 0, 0, 0.4)',
    '--tip-link': '#93c5fd',
    '--tip-muted': '#94a3b8',
  },
  dark: {
    '--bg': '#0c1a3a',
    '--text': '#dbeafe',
    '--muted': '#94a3b8',
    '--board': '#1e2a5e',
    '--header-bg': '#2e3b78',
    '--header-text': '#dbeafe',
    '--cell': '#1e2a5e',
    '--tile': '#60a5fa',
    '--tile-hover': '#3b82f6',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#1a2550',
    '--tile-correct-border': '#93c5fd',
    '--tile-correct-text': '#dbeafe',
    '--success-bg': '#2563eb',
    '--success-text': '#ffffff',
    '--success-link': '#bfdbfe',
    '--accent': '#93c5fd',
    '--accent-soft': '#1e2a5e',
    '--btn': '#3b82f6',
    '--btn-hover': '#60a5fa',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#2e3b78',
    '--btn-secondary-hover': '#3e4d92',
    '--btn-secondary-text': '#dbeafe',
    '--win': '#93c5fd',
    '--win-glow': 'rgba(147, 197, 253, 0.5)',
    '--banner-bg': '#1e2a5e',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#060e25',
    '--tip-text': '#dbeafe',
    '--tip-border': '#2e3b78',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#93c5fd',
    '--tip-muted': '#94a3b8',
  },
};

/* ============================================================
   MUTED — original autumnal blue-gray
   ============================================================ */
export const MUTED_THEME = {
  name: 'muted',
  light: {
    '--bg': '#f4f5f7',
    '--text': '#2a2f3a',
    '--muted': '#6b7280',
    '--board': '#e5e7eb',
    '--header-bg': '#d6dae1',
    '--header-text': '#374151',
    '--cell': '#fbfcfd',
    '--tile': '#5b7cb8',
    '--tile-hover': '#486aa6',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#eaeef5',
    '--tile-correct-border': '#1d3f6e',
    '--tile-correct-text': '#1d3f6e',
    '--success-bg': '#1d3f6e',
    '--success-text': '#ffffff',
    '--success-link': '#b8d2f2',
    '--accent': '#5b7cb8',
    '--accent-soft': '#dbe4f3',
    '--btn': '#5b7cb8',
    '--btn-hover': '#486aa6',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#e5e7eb',
    '--btn-secondary-hover': '#d1d5db',
    '--btn-secondary-text': '#374151',
    '--win': '#2f5d9a',
    '--win-glow': 'rgba(91, 124, 184, 0.45)',
    '--banner-bg': '#ffffff',
    '--banner-shadow': 'rgba(20, 30, 50, 0.18)',
    '--tip-bg': '#1a1f2e',
    '--tip-text': '#e4e6eb',
    '--tip-border': '#374151',
    '--tip-shadow': 'rgba(0, 0, 0, 0.35)',
    '--tip-link': '#b8d2f2',
    '--tip-muted': '#9ca3af',
  },
  dark: {
    '--bg': '#1a1d24',
    '--text': '#e4e6eb',
    '--muted': '#8b92a3',
    '--board': '#0f1219',
    '--header-bg': '#2a2f3a',
    '--header-text': '#c4cad5',
    '--cell': '#20242d',
    '--tile': '#4f6fa3',
    '--tile-hover': '#6184bf',
    '--tile-text': '#ffffff',
    '--tile-correct-bg': '#1f2940',
    '--tile-correct-border': '#8ab0e8',
    '--tile-correct-text': '#b8d2f2',
    '--success-bg': '#2f5d9a',
    '--success-text': '#ffffff',
    '--success-link': '#b8d2f2',
    '--accent': '#6184bf',
    '--accent-soft': '#2c3a52',
    '--btn': '#4f6fa3',
    '--btn-hover': '#6184bf',
    '--btn-text': '#ffffff',
    '--btn-secondary-bg': '#2a2f3a',
    '--btn-secondary-hover': '#353b48',
    '--btn-secondary-text': '#c4cad5',
    '--win': '#8ab0e8',
    '--win-glow': 'rgba(138, 176, 232, 0.5)',
    '--banner-bg': '#2a2f3a',
    '--banner-shadow': 'rgba(0, 0, 0, 0.5)',
    '--tip-bg': '#0a0d14',
    '--tip-text': '#e4e6eb',
    '--tip-border': '#2a2f3a',
    '--tip-shadow': 'rgba(0, 0, 0, 0.6)',
    '--tip-link': '#b8d2f2',
    '--tip-muted': '#8b92a3',
  },
};

/* ============================================================
   THEMES — lookup by name
   ============================================================ */
export const THEMES = {
  sky: SKY_THEME,
  periwinkle: PERIWINKLE_THEME,
  teal: TEAL_THEME,
  slate: SLATE_THEME,
  azure: AZURE_THEME,
  muted: MUTED_THEME,
};

export default THEMES;