// utils/mathProofThemes.js

const themes = {
    default: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '24px',
        background: '#ffffff',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: '600',
        margin: '0 0 28px 0',
        color: '#1a202c',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '18px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.07), 0 1px 3px rgba(0,0,0,0.1)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #e2e8f0',
      },
      stepNumber: {
        backgroundColor: '#4f46e5',
        color: 'white',
        borderRadius: '50%',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '16px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.6',
        color: '#1a202c',
      },
      arrow: {
        margin: '6px 0',
        color: '#4f46e5',
        fontSize: '28px',
        // fontWeight: '300',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#718096',
        border: '1px dashed #cbd5e0',
        borderRadius: '8px',
      }
    },
    tailwind_alert: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '24px',
        background: '#eff6ff',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: '600',
        margin: '0 0 28px 0',
        color: '#1e47b6',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '18px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.07), 0 1px 3px rgba(0,0,0,0.1)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '0.5px solid #1e47b6',
      },
      stepNumber: {
        backgroundColor: '#4f46e5',
        color: 'white',
        borderRadius: '50%',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '16px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.6',
        color: '#405ab3',
      },
      arrow: {
        margin: '6px 0',
        color: '#4f46e5',
        fontSize: '28px',
        // fontWeight: '300',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#718096',
        border: '1px dashed #cbd5e0',
        borderRadius: '8px',
      }
    },
    tailwind_alert_reversed: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '24px',
        background: '#ffffff',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: '600',
        margin: '0 0 28px 0',
        color: '#1e47b6',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '18px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#eff6ff',
        borderRadius: '8px',
        padding: '20px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.07), 0 1px 3px rgba(0,0,0,0.1)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '0.5px solid #1e47b6',
      },
      stepNumber: {
        backgroundColor: '#4f46e5',
        color: 'white',
        borderRadius: '50%',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '16px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.6',
        color: '#405ab3',
      },
      arrow: {
        margin: '6px 0',
        color: '#4f46e5',
        fontSize: '28px',
        // fontWeight: '300',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#718096',
        border: '1px dashed #cbd5e0',
        borderRadius: '8px',
      }
    },
    
    
    
    modern: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '28px',
        background: '#fafafa',
      },
      title: {
        textAlign: 'center',
        fontSize: '28px',
        fontWeight: '700',
        margin: '0 0 32px 0',
        color: '#111827',
        letterSpacing: '-0.025em',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: '12px',
        padding: '24px',
        boxShadow: '0 10px 15px -3px rgba(0,0,0,0.05), 0 4px 6px -2px rgba(0,0,0,0.025)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #f3f4f6',
      },
      stepNumber: {
        backgroundColor: '#000000',
        color: 'white',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '18px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '17px',
        lineHeight: '1.7',
        color: '#1f2937',
      },
      arrow: {
        margin: '8px 0',
        color: '#000000',
        fontSize: '20px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '28px',
        color: '#6b7280',
        backgroundColor: '#ffffff',
        border: '1px solid #f3f4f6',
        borderRadius: '12px',
        boxShadow: '0 10px 15px -3px rgba(0,0,0,0.05), 0 4px 6px -2px rgba(0,0,0,0.025)',
      }
    },
    
    elegant: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '30px',
        background: '#ffffff',
      },
      title: {
        textAlign: 'center',
        fontSize: '24px',
        fontWeight: '500',
        margin: '0 0 36px 0',
        color: '#1e293b',
        borderBottom: '1px solid #e2e8f0',
        paddingBottom: '12px',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '28px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: '6px',
        padding: '22px',
        boxShadow: '0 1px 3px rgba(0,0,0,0.05)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #e2e8f0',
      },
      stepNumber: {
        backgroundColor: '#475569',
        color: 'white',
        borderRadius: '50%',
        width: '28px',
        height: '28px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '500',
        marginRight: '16px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.8',
        color: '#334155',
      },
      arrow: {
        margin: '8px 0',
        color: '#475569',
        fontSize: '16px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '26px',
        color: '#64748b',
        backgroundColor: '#f8fafc',
        border: '1px solid #e2e8f0',
        borderRadius: '6px',
      }
    },
    
    tech: {
      container: {
        fontFamily: 'system-ui, -apple-system, monospace',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '24px',
        background: '#0f172a',
        color: '#e2e8f0',
        borderRadius: '8px',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: '600',
        margin: '0 0 28px 0',
        color: '#f8fafc',
        letterSpacing: '0.025em',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#1e293b',
        borderRadius: '6px',
        padding: '20px',
        boxShadow: '0 4px 6px rgba(0,0,0,0.2)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #334155',
      },
      stepNumber: {
        backgroundColor: '#10b981',
        color: '#0f172a',
        borderRadius: '4px',
        width: '28px',
        height: '28px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '16px',
        flexShrink: 0,
        fontFamily: 'monospace',
      },
      stepContent: {
        fontSize: '15px',
        lineHeight: '1.6',
        color: '#f1f5f9',
      },
      arrow: {
        margin: '6px 0',
        color: '#10b981',
        fontSize: '18px',
        fontWeight: 'bold',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#94a3b8',
        backgroundColor: '#1e293b',
        border: '1px dashed #475569',
        borderRadius: '6px',
      }
    },
    
    academic: {
      container: {
        fontFamily: '"Times New Roman", Times, serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '30px',
        background: '#ffffff',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: 'bold',
        margin: '0 0 30px 0',
        color: '#000000',
        borderBottom: '2px solid #000000',
        paddingBottom: '10px',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#ffffff',
        borderRadius: '0',
        padding: '20px',
        boxShadow: 'none',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #d1d5db',
      },
      stepNumber: {
        backgroundColor: '#ffffff',
        color: '#000000',
        borderRadius: '0',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        marginRight: '16px',
        flexShrink: 0,
        border: '1px solid #000000',
      },
      stepContent: {
        fontSize: '18px',
        lineHeight: '1.6',
        color: '#000000',
      },
      arrow: {
        margin: '8px 0',
        color: '#000000',
        fontSize: '18px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#6b7280',
        border: '1px solid #d1d5db',
      }
    },
    
    dark: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
        backgroundColor: '#1a1a1a',
        color: '#f0f0f0',
      },
      title: {
        textAlign: 'center',
        fontSize: '24px',
        fontWeight: 'bold',
        margin: '0 0 20px 0',
        color: '#f0f0f0',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '16px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#2d2d2d',
        borderRadius: '8px',
        padding: '16px',
        boxShadow: '0 2px 4px rgba(0,0,0,0.3)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #444',
      },
      stepNumber: {
        backgroundColor: '#6366f1',
        color: 'white',
        borderRadius: '50%',
        width: '28px',
        height: '28px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        marginRight: '12px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.5',
        color: '#e0e0e0',
      },
      arrow: {
        margin: '8px 0',
        color: '#6366f1',
        fontSize: '20px',
        fontWeight: 'bold',
      },
      emptyState: {
        textAlign: 'center',
        padding: '20px',
        color: '#999',
        border: '1px dashed #666',
        borderRadius: '8px',
      }
    },
    
    minimal: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
      },
      title: {
        textAlign: 'center',
        fontSize: '20px',
        fontWeight: 'normal',
        margin: '0 0 20px 0',
        color: '#333',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '12px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: 'transparent',
        borderRadius: '0',
        padding: '12px',
        boxShadow: 'none',
        display: 'flex',
        alignItems: 'flex-start',
        borderBottom: '1px solid #eaeaea',
      },
      stepNumber: {
        backgroundColor: 'transparent',
        color: '#666',
        borderRadius: '0',
        width: '24px',
        height: '24px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        marginRight: '12px',
        flexShrink: 0,
        border: '1px solid #ccc',
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.5',
        color: '#333',
      },
      arrow: {
        margin: '4px 0',
        color: '#666',
        fontSize: '16px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '16px',
        color: '#999',
        borderBottom: '1px solid #eaeaea',
      }
    },
    
    colorful: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '20px',
        background: '#f5f7fa',
      },
      title: {
        textAlign: 'center',
        fontSize: '28px',
        fontWeight: 'bold',
        margin: '0 0 20px 0',
        color: '#4338ca',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '20px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        background: '#f6f9ff',
        borderRadius: '12px',
        padding: '20px',
        boxShadow: '0 8px 16px rgba(71, 84, 255, 0.1)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid rgba(67, 56, 202, 0.2)',
      },
      stepNumber: {
        background: '#667eea',
        color: 'white',
        borderRadius: '50%',
        width: '32px',
        height: '32px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'bold',
        marginRight: '16px',
        flexShrink: 0,
        boxShadow: '0 4px 6px rgba(50, 50, 93, 0.11)',
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.6',
        color: '#4a5568',
      },
      arrow: {
        margin: '10px 0',
        color: '#667eea',
        fontSize: '24px',
        fontWeight: 'bold',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#a0aec0',
        background: '#f6f9ff',
        borderRadius: '12px',
        boxShadow: '0 8px 16px rgba(71, 84, 255, 0.1)',
        border: '1px dashed #667eea',
      }
    },
    
    paper: {
      container: {
        fontFamily: 'Georgia, serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '30px',
        backgroundColor: '#ffffff',
        boxShadow: '0 4px 10px rgba(0,0,0,0.05)',
        borderRadius: '2px',
      },
      title: {
        textAlign: 'center',
        fontSize: '26px',
        fontWeight: 'normal',
        margin: '0 0 30px 0',
        color: '#382110',
        borderBottom: '1px solid #e8e0d0',
        paddingBottom: '10px',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '24px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#fffbeb',
        borderRadius: '2px',
        padding: '20px',
        boxShadow: '0 1px 4px rgba(0,0,0,0.05)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #e8e0d0',
      },
      stepNumber: {
        backgroundColor: '#8c7851',
        color: '#fffdf7',
        borderRadius: '50%',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: 'normal',
        marginRight: '16px',
        flexShrink: 0,
        fontFamily: 'Georgia, serif',
      },
      stepContent: {
        fontSize: '17px',
        lineHeight: '1.7',
        color: '#382110',
        fontFamily: 'Georgia, serif',
      },
      arrow: {
        margin: '10px 0',
        color: '#8c7851',
        fontSize: '18px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '24px',
        color: '#8c7851',
        borderRadius: '2px',
        backgroundColor: '#fffef9',
        border: '1px dashed #e8e0d0',
        fontFamily: 'Georgia, serif',
      }
    },
    
    gradientBlue: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '30px',
        background: '#e0f2fe',
        borderRadius: '16px',
      },
      title: {
        textAlign: 'center',
        fontSize: '28px',
        fontWeight: '700',
        margin: '0 0 30px 0',
        color: '#1e40af',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '22px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        background: '#ffffff',
        borderRadius: '12px',
        padding: '22px',
        boxShadow: '0 8px 16px rgba(59, 130, 246, 0.15)',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #93c5fd',
      },
      stepNumber: {
        background: '#3b82f6',
        color: 'white',
        borderRadius: '50%',
        width: '36px',
        height: '36px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        marginRight: '18px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '17px',
        lineHeight: '1.7',
        color: '#1e3a8a',
      },
      arrow: {
        margin: '8px 0',
        color: '#3b82f6',
        fontSize: '24px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '28px',
        color: '#60a5fa',
        background: '#ffffff',
        border: '1px dashed #60a5fa',
        borderRadius: '12px',
        boxShadow: '0 8px 16px rgba(59, 130, 246, 0.15)',
      }
    },
    
    chalkboard: {
      container: {
        fontFamily: 'system-ui, monospace',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '35px 30px',
        background: '#2d3748',
        borderRadius: '8px',
        border: '10px solid #4a5568',
      },
      title: {
        textAlign: 'center',
        fontSize: '32px',
        fontWeight: '700',
        margin: '0 0 35px 0',
        color: '#f7fafc',
        fontFamily: 'monospace',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: 'transparent',
        borderRadius: '0',
        padding: '20px',
        display: 'flex',
        alignItems: 'flex-start',
        borderBottom: '2px dashed #a0aec0',
        position: 'relative',
      },
      stepNumber: {
        backgroundColor: '#f56565',
        color: 'white',
        borderRadius: '50%',
        width: '40px',
        height: '40px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '800',
        marginRight: '20px',
        flexShrink: 0,
        fontFamily: 'monospace',
        fontSize: '20px',
      },
      stepContent: {
        fontSize: '18px',
        lineHeight: '1.8',
        color: '#ffffff',
        fontFamily: 'monospace',
      },
      arrow: {
        margin: '10px 0',
        color: '#f56565',
        fontSize: '30px',
        fontWeight: 'bold',
      },
      emptyState: {
        textAlign: 'center',
        padding: '30px',
        color: '#e2e8f0',
        borderBottom: '2px dashed #a0aec0',
        fontFamily: 'monospace',
      }
    },
    
    blueprint: {
      container: {
        fontFamily: 'monospace',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '30px',
        background: '#172554',
        border: '2px solid #3b82f6',
        borderRadius: '4px',
      },
      title: {
        textAlign: 'center',
        fontSize: '24px',
        fontWeight: '500',
        margin: '0 0 30px 0',
        color: '#bfdbfe',
        textTransform: 'uppercase',
        letterSpacing: '2px',
        borderBottom: '1px solid #60a5fa',
        paddingBottom: '15px',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: 'rgba(23, 37, 84, 0.9)',
        borderRadius: '4px',
        padding: '20px',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #60a5fa',
      },
      stepNumber: {
        backgroundColor: '#bfdbfe',
        color: '#172554',
        borderRadius: '4px',
        width: '30px',
        height: '30px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '700',
        marginRight: '15px',
        flexShrink: 0,
        border: '1px solid #60a5fa',
      },
      stepContent: {
        fontSize: '15px',
        lineHeight: '1.6',
        color: '#dbeafe',
        fontFamily: 'monospace',
      },
      arrow: {
        margin: '10px 0',
        color: '#60a5fa',
        fontSize: '20px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '25px',
        color: '#93c5fd',
        backgroundColor: 'rgba(23, 37, 84, 0.9)',
        border: '1px dashed #60a5fa',
        borderRadius: '4px',
      }
    },
    
    neonNight: {
      container: {
        fontFamily: 'system-ui, -apple-system, sans-serif',
        maxWidth: '800px',
        margin: '0 auto',
        padding: '35px',
        background: '#09090b',
        borderRadius: '16px',
        border: '1px solid #7e22ce',
      },
      title: {
        textAlign: 'center',
        fontSize: '30px',
        fontWeight: '700',
        margin: '0 0 30px 0',
        color: '#c084fc',
        letterSpacing: '1px',
      },
      stepsContainer: {
        display: 'flex',
        flexDirection: 'column',
        gap: '25px',
      },
      stepWrapper: {
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
      },
      stepCard: {
        width: '100%',
        backgroundColor: '#18181b',
        borderRadius: '12px',
        padding: '25px',
        display: 'flex',
        alignItems: 'flex-start',
        border: '1px solid #7e22ce',
      },
      stepNumber: {
        background: '#c026d3',
        color: 'white',
        borderRadius: '50%',
        width: '36px',
        height: '36px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontWeight: '600',
        marginRight: '20px',
        flexShrink: 0,
      },
      stepContent: {
        fontSize: '16px',
        lineHeight: '1.7',
        color: '#e4e4e7',
      },
      arrow: {
        margin: '10px 0',
        color: '#c084fc',
        fontSize: '24px',
      },
      emptyState: {
        textAlign: 'center',
        padding: '30px',
        color: '#a1a1aa',
        backgroundColor: '#18181b',
        border: '1px dashed #7e22ce',
        borderRadius: '12px',
      }
    },
    
    vintage: {
        container: {
          fontFamily: 'Georgia, serif',
          maxWidth: '800px',
          margin: '0 auto',
          padding: '40px 30px',
          background: '#f5f5dc',
          border: '8px solid #8b4513',
          borderRadius: '2px',
        },
        title: {
          textAlign: 'center',
          fontSize: '32px',
          fontWeight: 'normal',
          margin: '0 0 35px 0',
          color: '#8b4513',
          fontFamily: 'Georgia, serif',
          borderBottom: '2px solid #d2b48c',
          paddingBottom: '15px',
        },
        stepsContainer: {
          display: 'flex',
          flexDirection: 'column',
          gap: '30px',
        },
        stepWrapper: {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
        },
        stepCard: {
          width: '100%',
          backgroundColor: '#fff8dc',
          borderRadius: '0',
          padding: '25px',
          boxShadow: '5px 5px 0px #8b4513',
          display: 'flex',
          alignItems: 'flex-start',
          border: '2px solid #8b4513',
          position: 'relative',
        },
        stepNumber: {
          backgroundColor: '#8b4513',
          color: '#f5f5dc',
          borderRadius: '50%',
          width: '40px',
          height: '40px',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          fontWeight: 'bold',
          marginRight: '20px',
          flexShrink: 0,
          fontFamily: 'Georgia, serif',
          fontSize: '20px',
          border: '2px solid #d2b48c',
        },
        stepContent: {
          fontSize: '18px',
          lineHeight: '1.8',
          color: '#5c4033',
          fontFamily: 'Georgia, serif',
        },
        arrow: {
          margin: '15px 0',
          color: '#8b4513',
          fontSize: '26px',
          fontWeight: 'bold',
        },
        emptyState: {
          textAlign: 'center',
          padding: '30px',
          color: '#8b4513',
          backgroundColor: '#fff8dc',
          border: '2px dashed #8b4513',
          fontFamily: 'Georgia, serif',
        }
      },
    }

    export default themes;